### ISSUE TITLE
No latex generated for register or bitfield values

### ISSUE THREAD

**Issue by arichardson** [rems-project/sail#110]
sail-cheri-mips has the following
```
bitfield CapCauseReg : bits(16) = {
  ExcCode : 15..8,
  RegNum : 7..0,
}

register CapCause : CapCauseReg
register CID : bits(64)
```
but there is no generate latex for it, resulting in missing references to `sailMIPSzExcCode` and `sailMIPSzRegNum`

**Comment by bacam** [comment]
I've added register support.  Bitfields are automatically expanded before LaTeX is produced at the moment, so produce unhelpful type definitions.  I'll see if I can turn that off.

**Comment by bacam** [comment]
That wasn't quite true - it does appear to work with `-new_bitfields`, but I don't think the RISC-V model is compatible with that.
