### ISSUE TITLE
problem about list

### ISSUE THREAD

**Issue by zilongwang123** [rems-project/sail#114]
val list_test : list(int) -> unit

function list_test(a) = {
    match a {
        a :: li => {print("1"); list_test(li)},
        [||] => print("end")
    }
}

If the input is an empty  list, It will be error"Error: Failure: Cannot match cons pattern against non-list".

**Comment by Alasdair** [comment]
Fixed

In future it would be useful if you mention how to reproduce the bug, because as far as I can tell this only affects the interactive interpreter and not any of the main backends.
