### ISSUE TITLE
Issue in installing SAIL on Ubuntu 18.04

### ISSUE THREAD

**Issue by Vasanvs** [rems-project/sail#119]
Hi all,

I am using Ubuntu 18.04 and trying to install SAIL in this machine. However, if I install SAIL as a module and as well as from git repository, it is giving errors.

My current ocaml version is 4.05
If I try to switch to 4.06.1, I get an error

$ ocaml --version
The OCaml toplevel, version 4.05.0
$ opam switch create 4.06.1
opam: Invalid switch subcommand "create"
Usage: opam switch [OPTION]... [COMMAND] [ARG]...
Try `opam switch --help' or `opam --help' for more information.

After installing the system dependencies, if I try to do opam install sail, I get an error:
$ opam install sail
[ERROR] No package named sail found.

If I try to install a development version of SAIL,  I get an error:
$ git clone https://github.com/rems-project/sail.git
$ cd sail
$ opam pin add sail .

Package sail does not exist, create as a NEW package ? [Y/n] Y
sail is now path-pinned to /home/vasan/RVI/shakti-tools/sail

[sail] /home/vasan/RVI/shakti-tools/sail/ synchronized
[ERROR] File "/home/vasan/.opam/system/packages.dev/sail/opam", line 50, character 37-38: parse error.
[WARNING] Errors in opam file from sail source, ignored (fix with 'opam pin edit')

[ERROR] File "/home/vasan/.opam/system/overlay/sail/opam_", line 50, character 37-38: parse error.
Invalid opam file:
    error  1: File does not parse

----

Is there any specific dependency that is missing here for the installation to fail? 

Thanks

**Comment by bacam** [comment]
Hi,

It sounds like you have an old version of opam which can't use the current opam repositories.  You can check with `opam --version`.  If you have a version older than 2 you should upgrade, for example by using [these installation instructions on the opam website](https://opam.ocaml.org/doc/Install.html).

**Comment by Vasanvs** [comment]
Thanks much Brain for your inputs. It was indeed the issue as opam version was very old for some reason. 

After upgrading it, sail has got successfully installed.

Thanks again
