### ISSUE TITLE
Undefined reference error in C

### ISSUE THREAD

**Issue by rbanerjee20** [rems-project/sail#136]
Hello,

I'm getting an error when trying to compile a Sail-generated C file for a program that works when using the OCaml emulator.

Here's the Sail code that produces the error. 

```ml
$include <prelude.sail>

type instruction = bits(16)

val list_index : forall('n : Int), ('n >= 1). (list(bits('n)), int) -> bits('n)
function list_index ((instr :: rest), i) = 
  match i {
    0 => instr,
    _ => list_index(rest, i - 1)
  }

val main : unit -> unit
function main () = {
  instrs : list(instruction) = [|0x0001|];
  print_bits("Instr: ", list_index(instrs, 0))
}
```

This program compiles successfully to both OCaml and C. The OCaml executes as expected, printing `Instr: 0x0001`. However, when I try to compile the C file I get from Sail (`out_c.c`), I get the following error:

```bash
warning: implicit declaration of function ‘convert_zz5listz8z5bvz9_of_zz5listz8z5bv16z9’ [-Wimplicit-function-declaration]
   37 | #define CONVERT_OF(type1, type2) convert_ ## type1 ## _of_ ## type2
      |                                  ^~~~~~~~
out_c.c:2762:5: note: in expansion of macro ‘CONVERT_OF’
 2762 |     CONVERT_OF(zz5listz8z5bvz9, zz5listz8z5bv16z9)(&zgsz321, zinstrs);
      |     ^~~~~~~~~~
/usr/bin/ld: /tmp/ccnpe5N0.o: in function `zmain':
out_c.c:(.text+0x5327): undefined reference to `convert_zz5listz8z5bvz9_of_zz5listz8z5bv16z9'
collect2: error: ld returned 1 exit status
```

**Comment by Alasdair** [comment]
I'll look into it, I think I know what's going on

**Comment by Alasdair** [comment]
Fixed in https://github.com/rems-project/sail/commit/ee43c8dedf13e9a17c8d289faa1294dffa1ddb39

Sorry for taking a while to fix this, I had various paper deadlines earlier this month that were keeping me very occupied.

**Comment by rbanerjee20** [comment]
No problem - thanks very much for the fix.
