### ISSUE TITLE
Expected usage of random generators produced by -ocaml_generators

### ISSUE THREAD

**Issue by rbanerjee20** [rems-project/sail#140]
Hello,

I know from Sail's CLI that the usage of the `ocaml_generators` flag is as follows:

```
-ocaml_generators <types>                produce random generators for the given types
```

I can also see that when I run a command such as `./sail -ocaml helloWorld.sail -ocaml_generators bit`, the output OCaml file `out.ml` contains the following lines at the end:

```ml
type generators = {gen_zbit: generators -> bit}

let rand_gens : generators = {gen_zbit = rand_zbit}
```

and looking at [sail_lib.ml](https://github.com/rems-project/sail/blob/91090bfee5c898c7597a06a0d92a05847c1e07f6/src/sail_lib.ml#L1189), I understand that `rand_zbit` produces B0 or B1 with probability 0.5 each. 

My question is, is there any recommended usage of the random generators produced by this flag (such as `rand_zbit` in this example)? Either by directly tinkering with the OCaml file `out.ml` or something in relation to the `out` binary file?

Many thanks for your help!

**Comment by bacam** [comment]
Sorry, accidentally closed the wrong issue.

So far the only use of this feature was for the TestRIG generator at https://github.com/rems-project/sail-riscv-test-generation.  When I've a bit more time I'll add some notes to the manual.

**Comment by bacam** [comment]
I've added some brief explanation to the manual now.  I've also fixed a bug that was introduced in the generators support since it was last used, so if you're using them you should update Sail to the latest git commit.
