### ISSUE TITLE
Performance in executing generated Coq definitions

### ISSUE THREAD

**Issue by xxuejie** [rems-project/sail#146]
Hi there,

Lately we've been trying with the Coq backend of sail. I tried generating Coq definitions for [sail-riscv](https://github.com/riscv/sail-riscv) (I know, sail-riscv now is a different repo for a different organization, but I do suspect the question is better suited for the sail project). Then I put together some basic Coq code:

```
Require riscv.
Compute (riscv.decode ('b"00011001111100001101000011101111" : mword 32)).
```

Here I'm merely decoding a RISC-V instruction, this operation alone takes about 5 minutes to run, comsuming more than 20GB of memory.

If I use a slightly more complicated operation, doing both decoding and executing:

```
Require riscv.
Compute ((riscv.decode ('b"00011001111100001101000011101111" : mword 32)) >>= riscv.execute).
```

This will be killed by the OS due to OOM errors.

I'm testing this on a headless Ubuntu 20.04 machine with AMD Ryzen 3900x + 64GB memory. So I wonder my computer might not be the bottleneck here :)

My question is: is there anything I'm doing wrong, or is this expected from the Coq file generated by sail? Any tips for getting the code to run more efficient than the numbers above?

Just to provide more complete information, I'm running the following versions of software:

* OCaml: 4.12.0 installed using default options of opam
* Coq: 8.13.2
* Sail: installed from source as of [the latest commit at the time of writing](https://github.com/rems-project/sail/commit/91cfbbc346567c8b8a17e37c398b61b8ee0f3e6a).
* Sail-riscv: [the latest commit at the time of writing](https://github.com/riscv/sail-riscv/commit/9f71c756484a4aac7c211d5ea266f45b0b3942e7)

Many thanks!

**Comment by bacam** [comment]
Hi,

There are two problems which are causing trouble.  The first is that bbv's binary notation produces a unary `nat` before constructing the bitvector, making it very expensive.  The hex notation is OK though:
```
Compute (riscv.decode (Ox"19f0d0ef" : mword 32)).
    = Done
         (riscv_types.RISCV_JAL
            (Word.WS false
               (Word.WS true
...
```
The second is that execution of the instruction will stop at a register access but `Compute` will try to normalize the remainder of the computation, where something is blowing up in size.  Asking for the head-normal-form does work:
```
Eval hnf in (riscv.decode (Ox"19f0d0ef" : mword 32) >>= riscv.execute).
     = Read_reg (name riscv_types.PC_ref)
         (fun v : riscv_types.register_value =>
          match of_regval riscv_types.PC_ref v with
          | Some v0 => Done v0
          | None => Fail "read_reg: unrecognised value"
          end >>=
          (fun w__0 : mword 64 =>
           let t :=
             add_vec w__0
 ...
```
One tool that you might find useful for evaluation is the library included with Sail for lifting the monadic operations into a sequential state altering form.  When supplied with enough initial state this won't get stuck at register accesses.

**Comment by xxuejie** [comment]
Those tricks do the job, many thanks!

**Comment by xxuejie** [comment]
Those tricks do the job, many thanks!
