### ISSUE TITLE
Use of `atom(.)` and `let 'x = ...` in Sail

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#148]
I wonder about the meaning of the following two	constructs in Sail that I can't	find documentation on.

- `atom(.)`
- `let 'x = ...	in ...`

I think they are related. As an example of  their use,  consider Lines 91 - 94 in  `riscv_types.sail` see [1], where we find:

    type regno ('n : Int), 0 <= 'n < 32 = atom('n)

    val regidx_to_regno : bits(5) -> {'n, 0 <= 'n < 32. regno('n)}
    function regidx_to_regno b = let 'r = unsigned(b) in r

How is `atom(.)` different from `int(.)`, as both seem to be of kind `Int`? I'm particularly interested in how `'r` and `r` relate in the last line. It looks like `let 'r = ... in M` binds both	`r` and	`'r` in `M`.

[1] https://github.com/riscv/sail-riscv/blob/master/model/riscv_types.sail#L91-L94

**Comment by Alasdair** [comment]
The `atom(.)` syntax is the same as `int(.)`, I should add a deprecation warning for that I think. I used to get a lot of questions about why atom was called atom, so I allowed int to be used with a type-variable which I think is more intuitive. I didn't remove it for backwards-compatibility reasons though.

You can name type-variables using an as pattern like:
```
let x as bits('width) = ... in ...
```
The `let 'x = ...` syntax is then shorthand for
```
let x as bits('x) = ... in ... (* or int('x) etc *)
```

I would change those lines to:
```
type regno ('n : Int), 0 <= 'n < 32 = int('n)

val regidx_to_regno : bits(5) -> {'n, 0 <= 'n < 32. regno('n)}
function regidx_to_regno b = unsigned(b)
```

**Comment by martinberger** [comment]
Thanks, that makes a lot of sense. 

It might make sense to put this deprecation information into the  documentation. The RISCV Sail repo has 74 lines where `atom` is still used. Maybe this should be updated eventually?
