### ISSUE TITLE
Problem with type aliases in liquid refinements?

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#149]
Consider the following program:

    type X : Int = 32
    type regno ('n : Int), 0 <= 'n < X = int('n)
    type R = { 'n, 0 <= 'n < 32. regno('n) }

It type-checks fine. But if I replace  the explicit `32` in the last line by `X`, which works fine in the definition of `regno`, in other words, if I replace the last line by

    type R = { 'n, 0 <= 'n < X. regno('n) }

then the type-checker complains: `SMT solver returned unexpected status 1`. This might be a problem with propagating type aliases?

**Comment by lukehallbland** [comment]
This is also encountered if you do something like

`let max = 6
let my_vector : vector(max, dec, whatever) = [values]`

or

`let max = 6
type X : Int = max
let my_vector : vector(X, dec, whatever) = [values]`

**Comment by Alasdair** [comment]
At least the first example should be fixed by https://github.com/rems-project/sail/commit/694bfc121da43467c6c61c3a2331f4b1e5e86bcd

**Comment by Alasdair** [comment]
Second issue should be fixed by https://github.com/rems-project/sail/commit/9c8c7fc3a524158524ba12962d2ef91c47515f64

If you want to do a top-level type synonym, it should be
```
type max: Int = 6
```

**Comment by martinberger** [comment]
Thanks!
