### ISSUE TITLE
Sail tutorial macro \mrbfn

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#153]
The Sail tutorial [1]  has some sentences that appear to end prematurely. For example Section 4.1 ends: _"we can drop it and simply write:"_ The culprit seems to be the Latex macro ```\mrbfn{...}``` which seems to expand to the empty string.

[1] https://github.com/rems-project/sail/blob/sail2/manual.pdf

**Comment by bacam** [comment]
Are you sure that you're looking at an up-to-date copy?  I think this is a bug we fixed a while back and the current PDF has some following code (albeit on the next page).

**Comment by martinberger** [comment]
You are correct, I was looking at a version from June 2021, the latest version (July 2021) fixes this. Sorry for the hassle.
