### ISSUE TITLE
OCaml backend broken with > 246 union members

### ISSUE THREAD

**Issue by jrtc27** [rems-project/sail#165]
In the transition from Sail 1 to 2, https://github.com/rems-project/sail/commit/89f9c0e89ca3722e7248c70300c239374842b93e has been lost, and the RISC-V model is close to the limit for the number of non-constant constructors generated by the OCaml backend (for the ast union representing decoded instructions). This is causing issues for the P and V extension development; see https://github.com/riscv/sail-riscv/pull/132#issuecomment-987769583 and https://github.com/riscv/sail-riscv/issues/138#issuecomment-1034940188.

**Comment by Alasdair** [comment]
Should be fixed. I used polymorphic variants like in the commit you linked.

I also tried an alternative approach where I used the last constructor as an overflow constructor, and then generated extra variant types for the overflow cases but it seemed more complex for little benefit, assuming there are no actual issues with using polymorphic variants for this.

**Comment by martinberger** [comment]
@Alasdair is this fix already being picked up by opam?

**Comment by jrtc27** [comment]
You will need to opam pin a git clone until a new version is released

**Comment by martinberger** [comment]
> You will need to opam pin a git clone 

OK, this is not something we should do with the GitHub actions for the RISCV-Sail model.
