### ISSUE TITLE
Access to the sail repository

### ISSUE THREAD

**Issue by billmcspadden-riscv** [rems-project/sail#166]
How does one gain write access to the rems-project/sail repository?

I would like to push some syntax highlighting files (for vim) into the repo.
Currently,  I'm getting a git error ("ERROR: Permission to rems-project/sail.git denied to billmcspadden-riscv")
when I attempt to push my branch into the repo.  I'm assuming that
I do not have write permission to the repo, yes?

**Comment by PeterSewell** [comment]
For the sail repo, best make a pull request

Peter

**Comment by billmcspadden-riscv** [comment]
I guess I'm exposing my lack of knowledge about github methodology,
but here goes...

I thought that PRs were done by pushing a branch to the repository, and then
issuing a PR that pointed to the branch.   Is this not the case?

Bill Mc.

**Comment by Alasdair** [comment]
The way it works on github is you would make a branch on your own fork of the repository, then make a pull request from there

**Comment by billmcspadden-riscv** [comment]
Ah,  got it. 

Thanks, @Alasdair

**Comment by ric-almeida** [comment]
I went through that myself with another rems-project not too long ago. I did exactly what it says here: https://opensource.com/article/19/7/create-pull-request-github

Ricardo
[https://opensource.com/sites/default/files/lead-images/checklist_hands_team_collaboration.png]<https://opensource.com/article/19/7/create-pull-request-github>
How to create a pull request in GitHub - Opensource.com<https://opensource.com/article/19/7/create-pull-request-github>
Open a pull request by clicking the Create pull request button. This allows the repo's maintainers to review your contribution. From here, they can merge it if it is good, or they may ask you to make some changes.
opensource.com

________________________________

**Comment by billmcspadden-riscv** [comment]
Closing the issue.  Successfully submitted a PR.
