### ISSUE TITLE
Feature request:  __FILE__ and __LINE__ (or equivalent) added to Sail

### ISSUE THREAD

**Issue by billmcspadden-riscv** [rems-project/sail#175]
In C,  we have the __FILE__ and __LINE__ macros that are very useful
in generating debug messages.

The request is that the same functionality be added to Sail.

__FILE__ expands to a string that contains the file name.
__LINE__ expands to the line number on which __LINE__ is 
found (in the file __FILE__).

**Comment by Alasdair** [comment]
Added `__FILE__`, `__LINE__` and `__LOC__` in this commit:

https://github.com/rems-project/sail/commit/dbbad9ce6c6e2928de3f8eb82b43046324244c1d
