### ISSUE TITLE
Compile-time error for empty scattered union.

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#176]
If I compile (with  the latest Sail v0.14 from opam) a single file that just contains 
```
scattered union ast
end ast
```
with option `-c` I get a compile-time error `Error: Failure hd`, which, I imagine, is not intended.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/commit/e5958061a345205881bdbdb6b19a1aa85777e5bc
