### ISSUE TITLE
Feature request: Pattern matching for structs

### ISSUE THREAD

**Issue by tperami** [rems-project/sail#179]
Unless I'm mistaken it is not currently possible to do pattern matching with structs. This would be a nice addition. The syntax can be shamelessly stolen from OCaml if needed

**Comment by bacam** [comment]
For future reference, one of the reasons we were talking about this is for writing bidirectional mappings, which can't really work for structs without them.

**Comment by martinberger** [comment]
> For future reference, one of the reasons we were talking about this

Is there a plan to add pattern matching for structs?

**Comment by nwf-msr** [comment]
Cross-referencing #234.

**Comment by Alasdair** [comment]
Implemented now
