### ISSUE TITLE
-smt_auto option broken?

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#181]
I wanted to check some properties using the sail SMT functionality, so I tried the following trivial example:
```
$include <vector_dec.sail>

$counterexample
function prop_falsifiable (b : bits(1)) -> bool = b[0] == bitone
```
I ran `./sail -smt -smt_auto prop.sail` in a recent sail checkout and got the following output:
```
Checking counterexample: prop_falsifiable.smt2
Solver found counterexample: ok
Error:
Cannot parse sexpr as ctyp
```
The output of cvc4 when run on the generated smt2 file is:
```
sat
(model
(declare-datatypes ((Unit 0)) (((unit))))
(declare-datatypes ((Bits 0)) (((Bits (len (_ BitVec 8)) (contents (_ BitVec 256))))))
(declare-datatypes ((Zexception 0)) (((z__dummy_exnz3z3 (unz__dummy_exnz3z3 Unit)))))
(define-fun zz40/1 () (_ BitVec 1) #b0)
)
```
Am I doing something wrong?

Along the way I made a few other observations about sail's SMT support:

1. It requires CVC4? No problem but might be nice if documented. I think it crashed inelegantly when I tried to run it without CVC4 installed.
2. All arguments to the property have to be bits? That seems reasonable but I initially tried a bool and it gave an exception: `Fatal error: exception File "src/sail_smt_backend/smtlib.ml", line 659, characters 9-15: Assertion failed` A proper error message would be better...
3. You need to give `-smt` as well as `-smt_auto` option otherwise it parses and typechecks sail but doesn't call SMT solver? This confused me as I thought `-smt_auto` would imply `-smt`.

**Comment by bacam** [comment]
I've documented the CVC4 requirement in the only place `-smt_auto` appears to be documented at the moment - the command line help output.  It's rather unfortunate that we also have `-smt_solver` for Sail's type checker and not the SMT backend.  I think I'll leave that for another time though, along with working out how to get Sail's plugin system to automatically choose the backend when you give `-smt_auto`.
