### ISSUE TITLE
Syntax error during compiling my_replicate_bits.sail in doc/example

### ISSUE THREAD

**Issue by haitianzhishang** [rems-project/sail#182]
![截屏2022-08-25 19 44 42](https://user-images.githubusercontent.com/38684938/186655819-dd811820-9e4b-4429-bf36-ddfbd45d6c0d.png)
Error is gone if removing the "pure" keywords of all functions

Hope for some directions.

**Comment by bacam** [comment]
I missed this issue before, but it looks like you were trying to use it with an older version of Sail.
