### ISSUE TITLE
Unrecognized cval generating SMT using version 0.15

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#188]
I'm receiving an error when trying to generate SMT:
```
Error:
Unrecognised cval (zz42786/2, zz42784/2)
```
This worked in previous versions. I don't have a minimized test case yet.

**Comment by rmn30** [comment]
Looks like [smt_cval ](https://github.com/rems-project/sail/blob/sail2/src/sail_smt_backend/jib_smt.ml#L363) is missing a case for `V_tuple`?

**Comment by rmn30** [comment]
Test case:
```
$property
function prop () -> bool = {
    let (x, y) = (true, false);
    x
}
```
`sail -smt test.sail`
```
Error:
Unrecognised cval (true, false)
```

**Comment by Alasdair** [comment]
It'll be this commit I think:

https://github.com/rems-project/sail/commit/6c2c285633b5f15ad7a8fd30198adec4748fa6fa

Solution should be to split the C.struct_value flag into that and a separate C.tuple_value flag, which would be the old behavior before that commit.

Another fix could be to apply our tuple->named struct rewrite before, so tuples are represented as SMTLIB datatypes.

**Comment by rmn30** [comment]
Thanks. I've implemented this locally and it appears to work but now I don't think there are any uses of `C.tuple_value=true`?

**Comment by rmn30** [comment]
https://github.com/rems-project/sail/tree/tuple_value

**Comment by Alasdair** [comment]
isla will use C.tuple_value=true, but it lives in a separate repository
