### ISSUE TITLE
constrain about maximum non-constant constructors in ocaml emulator build

### ISSUE THREAD

**Issue by haitianzhishang** [rems-project/sail#192]
The error is below:
![截屏2023-01-05 11 48 48](https://user-images.githubusercontent.com/38684938/210697567-719ea95c-5b45-440d-a3f6-8623952a21ef.png)
Are there any solutions for this? The error is caused by that the type number of ast is more than 246.
![截屏2023-01-05 11 47 49](https://user-images.githubusercontent.com/38684938/210697423-b2257c86-77d0-462b-af08-9de1a182ed05.png)
Thanks a lot

**Comment by Alasdair** [comment]
Are you using the latest version of Sail? I think this was fixed by https://github.com/rems-project/sail/commit/e1b28aecddf46abafb8d4c5f9b2f303356ba5bb7

**Comment by haitianzhishang** [comment]
> Are you using the latest version of Sail? I think this was fixed by [e1b28ae](https://github.com/rems-project/sail/commit/e1b28aecddf46abafb8d4c5f9b2f303356ba5bb7)

Exactly, the version of sail I use is 0.14. I have updated and this error has been fixed.
Thanks a lot
