### ISSUE TITLE
Tutorial says it overloads rX and wX as X but it doesn't

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#195]
In the RISC-V tutorial in the manual it says:

> Finally we overload both the read (rX) and write (wX) functions as simply X. This allows us to write registers as X(r)= value and
read registers as value = X(r).

But it doesn't seem to actually do that in the code as far as I can see.

**Comment by Alasdair** [comment]
Should be fixed in the PDF now.

The code in the manual is pulled from this file https://github.com/rems-project/sail/blob/sail2/doc/examples/riscv_duopod.sail if you are interested in the plain source

**Comment by Timmmm** [comment]
That was fast, thanks!
