### ISSUE TITLE
C++ compilation fixes

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#197]
Using the generated C code from C++ is a bit awkward at the moment due to two things:

1. You're missing the magic C++ compatibility `#ifdef`s in the headers (e.g. `sail.h`):

```
#ifdef __cplusplus
extern "C" {
#endif

...

#ifdef __cplusplus
}
#endif
```

2. `sail.h` includes the line `bool not(const bool);` but `not` is a keyword in C++. I would say the simplest solution is to add a new alias `not_` and only expose `not` for C.

**Comment by Timmmm** [comment]
Actually an easier solution to the `not` problem is just to exclude it for C++. There's no reason you'd need to call it.

```
#ifndef __cplusplus
bool not(const bool);
#endif
```

**Comment by arichardson** [comment]
I'd also be interested in compiling it with a C++ compiler, so far I've just used a C file that includes the generated code and exposes individual functions to C++.
