### ISSUE TITLE
Coq translation of pattern matchings

### ISSUE THREAD

**Issue by lastland** [rems-project/sail#20]
Not sure if this is a known issue. The `execute` function on `ITYPE` in `riscv/riscv_duopod.sail` is defined as follow:
```
function clause execute (ITYPE (imm, rs1, rd, RISCV_ADDI)) =
  ... // function body
```
The pattern requires the fourth argument to be `RISCV_ADDI`. However, the Coq translation of this function does not reflect that, it is defined as follow:
```
Definition execute_ITYPE  (imm : mword 12) (rs1 : mword 5) (rd : mword 5) (RISCV_ADDI : iop)  
: M (unit):= ... (* function body *)
```
The `RISCV_ADDI` identifier here is just a parameter.

**Comment by bacam** [comment]
Thanks.  I've just added support for this.
