### ISSUE TITLE
How to cast bitvector to nat

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#200]
If I want to store a list of memory accesses (which can be different widths) then the obvious solution seems to be `list(nat)`, which I think will compile in C to a singly linked list of GMP arbitrary precision integers which is quite reasonable.

However I can't figure out how to convert a `bitvector` to `nat`. The manual mentions that implicit casting doesn't happen (very good!) but it doesn't say how to *explicitly* cast.

Alternatively is there a way to have type-erased `bitvectors` (i.e. where the length is not part of the type) so I could store them in a `list`?

**Comment by bacam** [comment]
Bitvectors and integers are distinct types in Sail, so it's a conversion rather than just a cast.  The `unsigned` function in the standard library does this - in fact, it's even more precise than `nat` because it also gives an upper bound for the result.

**Comment by Timmmm** [comment]
Ah I see, so it converts a `bitvector('n)` to `range(0, 2 ^ 'n)`? Perfect, thanks! Maybe worth adding to the docs...
