### ISSUE TITLE
Test generation?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#210]
On the [Cambridge web page](https://www.cl.cam.ac.uk/~pes20/sail/) it mentions using the Isla SMT output for test generation. I assume the idea is you can write properties like "A page table fault can never occur" or whatever, and then hit "prove" and it will come up with a counter-example.

But I can't find any examples of this or reference to it in the code. Has this actually been done or is it aspirational?

**Comment by Alasdair** [comment]
It's been done https://github.com/rems-project/isla-testgen

The page table code especially for ARM is a bit too complex though, so we've mostly used manual proof for properties about address translation.

**Comment by Timmmm** [comment]
Ah thanks for the (very fast) link! Not sure how I missed that! :-)

**Comment by Timmmm** [comment]
PS: Nice to see Rust! - When is the Rust backend for Sail coming? :-P

**Comment by Alasdair** [comment]
As useful as the borrow checker is, I think it would get in the way when using it as a compilation target
