### ISSUE TITLE
Feature request: entangle enums and mappings

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#212]
For every enumeration `E` Sail auto-generates maps from `E` to integers and integers to `E` (`num_of_E` and `E_of_num`). Those function map between the enum and an initial segment of the natural numbers.  Here is an example from the manual.

This hard-coding of a mapping is not always what we want. Often the numbers we want to associate with Enum constructors might be different e.g.

    function num_of_Foo(arg) = match arg {
      Bar => 666,
      Baz => 668,
      quux => 1999
    }

Of course we can code a suitable conversion function by hand, but I think it's neater to 'entangle' the definition of constructors directly with the definition of the conversion mapping, e.g.

      enum Foo = {
        Bar <-> 666,
        Baz <-> 668,
        quux <-> 1999}

This has two advantages

- Saves lines of code.

- Symbolic name (e.g. Bar) and numeric value (e.g. 666) are directly  adjacent, so easier for humans to check visually for agreement. This  would be useful for better integration of Sail with ISA manuals.

It would also appear to be completely backwards compatible, if we see

    enum Foo = {
      Bar,
      Baz,
      quux}

simply as an abbreviation of

    enum Foo = {
      Bar <-> 0,
      Baz <-> 1,
      quux <-> 2}

An interesting question is what the type of the mapping should be, e.g. bitwidth. There are various options.

**Comment by Alasdair** [comment]
You can currently do:

```
enum Foo with to_value -> int = {
    Bar => 666,
    Baz => 668,
    quux => 1999
}
```

and it'll create a Foo_to_value function. You can also use other types, and create multiple such functions:

```
enum E with as_bits -> bits(16), as_string -> string = {
  A => (0xFFFF, "A"),
  B => (0x0001, "B"),
  C => (sail_zeros(16), "C")
}
```

**Comment by martinberger** [comment]
@Alasdair  Brilliant. Can this also be used to construct bijective mappings, or just normal injective functions

But I don't think this is in the manual, no?

**Comment by Alasdair** [comment]
I don't think so.

I'm not sure how useful the bidirectional part is, the opposite direction would get a very awkward constraint:
```
val Foo_of_num : forall 'n, 'n in {666, 668, 1999}. int('n) -> Foo
```
which would make it hard to use. In general we don't want to be generating partial functions if we can avoid it.
