### ISSUE TITLE
Strip trailing whitespace (and maybe autoformat the code?)

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#225]
Is there any chance you could strip trailing whitespace on all the source code in this repo? I have my editor configured to do that and it would be nicer if I didn't end up with lots of random whitespace changes in my diff (yeah I can tell it not to for just this project but that seems silly).

I wonder if maybe it would even be a good idea to run [Ocamlformat](https://github.com/ocaml-ppx/ocamlformat) over the code since some of the indentation is very inconsistent!

**Comment by Alasdair** [comment]
I have been considering using OCamlformat, once I get some outstanding branches merged in

**Comment by arichardson** [comment]
I recently discovered `pre-commit` which makes management of pre-commit hooks a lot simpler. See https://github.com/CTSRD-CHERI/cheri-specification/commit/a434afa560a234ba15a030c7a4ecd0aaa6d6a390 for an example that enforces no trailing whitespace.

**Comment by Timmmm** [comment]
I second `pre-commit`, it's very good. Ideally you could use it to run `ocamlformat` too but unfortunately `ocamlformat` doesn't seem to support it yet.

**Comment by Alasdair** [comment]
https://github.com/rems-project/sail/pull/227

Rather than a pre-commit hook, we could also protect the main branch and have a GitHub action that checks the code is formatted before merging.

**Comment by arichardson** [comment]
> #227
> 
> Rather than a pre-commit hook, we could also protect the main branch and have a GitHub action that checks the code is formatted before merging.

Yeah what I did for the CHERI spec repository was add the pre-commit hook so it can be enforced locally, but also run it as part of the github CI: https://github.com/CTSRD-CHERI/cheri-specification/commit/0b0fcda11d4f88d593f5a00c82a767100978f109 That way we can check locally that everything is fine, and GitHub will enforce it for all contributors without the hooks installed locally.

**Comment by Alasdair** [comment]
Fixed via d4ed46039d615ae0ba477f36c93959f39d7389b6

**Comment by Timmmm** [comment]
Thanks for doing this - it's so much better! :tada:
