### ISSUE TITLE
Type checker confused about composed mappings

### ISSUE THREAD

**Issue by nwf-msr** [rems-project/sail#232]
Attempting to work around the lack of pattern matching for structs (#179), I have manually written some structure (un)packing mappings that shuffle things over to tuples and back.  Attempting to actually use these is proving somewhat problematic; they were accepted by the type-checker when that was all that was happening, but they are rejected by the typechecker when it comes time to emit C.  A minimized example of what I mean is
```
default Order dec
$include <prelude.sail>

enum E = EA | EB

mapping e_pair_bits : (E,E) <-> bits(2) =
  { (EA, EA) <-> 0b00
  , (EA, EB) <-> 0b01
  , (EB, EB) <-> 0b11
  }

struct eful =
  { e1 : E
  , e2 : E
  }

val eful_unpack : eful <-> (E,E)
function eful_unpack_forwards_matches(x) = true
function eful_unpack_forwards(s) = (s.e1, s.e2)
function eful_unpack_backwards_matches(x) = true
function eful_unpack_backwards(e1,e2) = struct { e1 = e1, e2 = e2 }

union F = { FE : eful }

val f_bits : F <-> bits(2)
mapping f_bits = { FE(eful_unpack(e1,e2)) <-> e_pair_bits(e1,e2) }
```

Running `Sail 0.15 (sail @ opam-v2.1.2)` with just the file as an argument terminates successfully with no error, as does running additionally with `-output_sail`, but adding `-c` elicits what I believe to be a bogus type failure:
```
sail -c ./test.sail
Type error:
Cannot bind tuple pattern (e1, e2) against non tuple type eful
```

**Comment by Alasdair** [comment]
I've added some support for struct patterns:

https://github.com/rems-project/sail/pull/234

**Comment by nwf-msr** [comment]
Oh nice; thanks, I'll go build from source and play with that.

For the present issue, tho', am I doing something wrong or is it actually a bug?

**Comment by Alasdair** [comment]
it's probably a bug, I'll have to take a look at what is causing it

**Comment by Alasdair** [comment]
Should be fixed now

**Comment by nwf-msr** [comment]
Thanks for this and for #234! <3
