### ISSUE TITLE
sail -fmt complains about /*! comments

### ISSUE THREAD

**Issue by arichardson** [rems-project/sail#237]
The sail-cheri-riscv model uses /*! comments for the LaTeX output, but if I run sail -fmt on the model I get the following error:
```
Lexical error:
src/cheri_cap_common.sail:83.1-1:
83 |/*! A partially decompressed version of a capability -- E, B, T,
   | ^
   | Unbalanced comment
make: *** [Makefile:257: format] Error 1
```

This goes away if I replace all /*! comments with /**.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/592
