### ISSUE TITLE
Scattered enums not considered scattered?

### ISSUE THREAD

**Issue by nwf-msr** [rems-project/sail#250]
This one I don't have a short reproducer for, I'm afraid.  I can try to generate one if necessary.

I have written
```
scattered enum InsnGroup
...
enum clause InsnGroup = InsnGroupA
```
and am being told
```
3 |enum clause InsnGroup = InsnGroupA
  |            ^-------^
  | Enumeration InsnGroup is not scattered - cannot add a new member with 'enum clause'
```
I'm not sure why Sail is confused here, but the example from #233 works fine and mine doesn't. :(

**Comment by Alasdair** [comment]
Hmm, not sure. I've added some additional information to the error message in https://github.com/rems-project/sail/pull/251

If there is both an `enum InsnGroup` and `scattered enum InsnGroup` it'll complain earlier about duplicating `InsnGroup`, so I'm not sure what could cause this. Does this error occur with `-just_check`?

**Comment by nwf-msr** [comment]
Yes, it occurs with `-just_check`.  I've managed to minimize it to...
```
scattered enum InsnGroup

val f : unit -> unit
function f() = ()

enum clause InsnGroup = InsnGroupMatchA
```

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/252
