### ISSUE TITLE
Type error: Tuple pattern and tuple type have different length  :  offending file and line number not given

### ISSUE THREAD

**Issue by billmcspadden-riscv** [rems-project/sail#277]
During RISCV model compilation,  I had a mismatch for the tuple pattern and tuple type.  A "type error" was given,  but no information about file and line number.  

Request:  supply file/line for both the pattern and the type.

**Comment by Alasdair** [comment]
Could you upload the code to a repo somewhere? It's quite hard to debug these kinds of issues without a way to reproduce locally

**Comment by billmcspadden-riscv** [comment]
@Alasdair :   I've created a branch in the sail-riscv repository that has the error:
hpm_events_billmcspadden__sail_error_message_is_terse

The error is at model/riscv_hpmevents.sail,  line 426.

Will this suffice?

**Comment by Alasdair** [comment]
Yes, thanks

**Comment by Alasdair** [comment]
Should be fixed now
