### ISSUE TITLE
C++ compilation

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#283]
Continuing from the discussion [here](https://github.com/rems-project/sail/pull/272) where I've been trying to compile multiple models in one binary, like this:

```
// model_rv32.cpp

namespace {
#include "riscv_rv32.c"
}

uint32_t getPc() { return zPC; }
...
```

And the same again for RV64.

Unfortunately it doesn't *quite* work because `riscv_rv32.c` is wrapped with

```
#ifdef __cplusplus
extern "C" {
#endif
```

And that actually makes all the symbols have external linkage despite the anonymous namespace (which results in duplicate symbols). I think the `extern "C"` stuff should be removed from the model output. I can't think of a situation where you'd want it.

**Comment by Alasdair** [comment]
I don't know anything about C++, so I'm not sure if @arichardson had a use-case that required this. We could make it an optional thing?

**Comment by Timmmm** [comment]
I don't think there's ever really a need for it.

`extern "C"` tells the C++ compiler to use C name mangling rules (I'm sure it's way more complicated than that but that's the main thing). It's useful when you want interoperate with code that was compiled with a C compiler so the symbol lookups don't go wrong. But that doesn't matter here since no C code is going to access the functions/variables defined in the model so it can just use C++ name mangling.

Btw another slight issue I found with the above approach is that the model has some `#include`s in it that end up in the `namespace { }` which is not what I want! For now I've just got a script to strip them but an option not to include anything might be nice.

Alternatively I guess I could use `-static`, but after discovering that `-c_prefix` doesn't really work I thought I'd go with `namespace { }` which is the same thing but can't miss anything.

**Comment by Timmmm** [comment]
Also I had a crazy/genius idea. Currently the output is kind of a pain to use because everything is global. Want two instances of the model? Nope!

But what about this...

```
class Runtime {
public:
    void platform_read_mem(lbits* data, int read_kind, uint64_t addr_size, sbits addr, const mpz_t n);
    bool platform_write_mem(const int write_kind, const uint64_t addr_size, const sbits addr, const mpz_t n, const lbits data);
    // ... all the other impure functions the model calls ...
private:
    std::unordered_map<uint64_t, uint8_t> m_ram;
};

class Model : public Runtime {
public:
    #include "generated_model.c"
};
```

Thanks to C++'s implicit `this`, all of the globals and references to globals now become class member variables/methods! No global state!

I haven't tried this yet though. I guess it could end up slightly slower due to passing `this` around everywhere but I doubt it's too bad.

**Comment by Timmmm** [comment]
Unfortunately wrapping the generated C code in `class Model { ... };` doesn't work out of the box because this isn't legal C++:

```
class Model {
void foo();
void foo() {
}
};
```

I might try modifying the compiler to omit the function declarations (or maybe just a regex to remove them). Probably not for a little while though.

**Comment by Timmmm** [comment]
> I might try modifying the compiler to omit the function declarations (or maybe just a regex to remove them). Probably not for a little while though.

I finally did this and it totally works. I hack the file like this:

    # Remove #include's
    text = re.sub(r"^([\t ]*#[\t ]*include.*)$", r"// \1", text, flags=re.MULTILINE)
    # Remove ifdef __cplusplus
    text = text.replace('#ifdef __cplusplus\nextern "C" {\n#endif\n', "")
    text = text.replace("#ifdef __cplusplus\n}\n#endif\n", "")
    # Remove function declarations
    text = re.sub(
        r"^((?:\w+[\t ]+)+\w+\([\w,* \t]*\);)$", r"// \1", text, flags=re.MULTILINE
    )
    # Remove `static` for static functions
    text = re.sub(r"^static ", "", text, flags=re.MULTILINE)

And then compile it like this:

```
namespace {
struct RiscvModel : public sail::ModelRuntime {
#include "riscv_model_rv32.c"
};
} // namespace
```

where `ModelRuntime` is a class that contains implementations for all the RTS functions:

```
struct ModelRuntime {

    unit write_tag_bool(uint64_t address, bool tag);
    bool read_tag_bool(uint64_t address) const;
    void platform_read_mem(lbits* data, int read_kind, uint64_t addr_size, sbits addr, const mpz_t n) const;
    bool platform_write_mem(
        const int write_kind, const uint64_t addr_size, const sbits addr, const mpz_t n, const lbits data);
    unit platform_write_mem_ea(const int write_kind, const uint64_t addr_size, const sbits addr, const mpz_t n);

    unit load_reservation(mach_bits addr);
    bool match_reservation(mach_bits addr) const;
    unit cancel_reservation(unit u);

    void set_speculate_conditional(bool succeed);
    bool speculate_conditional(unit u) const;

    unit platform_barrier_nop();

// Hack needed because barrier_kind seems to be generated?
#define platform_barrier(barrier_kind) platform_barrier_nop()

    void setup_rts();
    void cleanup_rts();

    int process_arguments(int argc, char* argv[]);

    int sail_coverage_exit();

    void sail_set_coverage_file(const char* output_file);
    void sail_function_entry(
        int function_id, const char* function_name, const char* sail_file, int l1, int c1, int l2, int c2);
    void sail_branch_reached(int branch_id, const char* sail_file, int l1, int c1, int l2, int c2);
    void sail_branch_target_taken(
        int branch_id, int branch_target_id, const char* sail_file, int l1, int c1, int l2, int c2);

    void sail_match_failure(const_sail_string msg);

    unit sail_assert(bool b, const_sail_string msg);
...
    std::map<uint64_t, uint8_t> m_memory;
    ...
};
```

And tada! It works. Multiple instances of the model work fine. There's no shared state... *except* unfortunately for these globals:

```
/*
 * Temporary mpzs for use in functions below. To avoid conflicts, only
 * use in functions that do not call other functions in this file.
 */
static sail_int sail_lib_tmp1, sail_lib_tmp2, sail_lib_tmp3;
static real sail_lib_tmp_real;
```

It doesn't affect instantiating multiple model instances, but it does mean they aren't thread safe. That's fine for my purposes.

**Comment by Timmmm** [comment]
Closing in favour of #547.
