### ISSUE TITLE
Unusual line number and column format in output

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#287]
Sail gives the complete line and column range for error messages by default:

```
Warning: Redundant case sail-riscv/model/riscv_sys_control.sail:206.6-7:
206 |      _ => false
    |      ^
```

Laudable, but this is an unusual format that tools like IDEs don't recognise by default. Would you accept a PR changing it to the far more standard format `filename:line:column:`?

**Comment by Alasdair** [comment]
Removing the range shouldn't be needed, switching to:
```
sail-riscv/model/riscv_sys_control.sail:206.6-7: Warning: Redundant case
206 |      _ => false
    |      ^
```
should be enough for most editors to pick it up correctly

**Comment by Timmmm** [comment]
Not VSCode unfortunately. It has no issue with the position - just the `206.6-7` ending. [It's link parsing code is extremely complex](https://github.com/microsoft/vscode/blob/3f769af4708aeb75065b7260e4fe801e0a8ed30d/src/vs/workbench/contrib/terminalContrib/links/browser/terminalLinkParsing.ts#L71) and supports a *lot* of formats but this isn't one of them. :-(

Based on that file you could do this:

```
Warning: Redundant case sail-riscv/model/riscv_sys_control.sail line 206-208 col 4-5
```

But I doubt that would be well supported by other editors. Perhaps something like this would be best:

```
Warning: Redundant case sail-riscv/model/riscv_sys_control.sail:206:4 - 208:5
```

I believe that would be recognised by most IDEs (including VSCode) and it retains the ending line/column.

**Comment by Alasdair** [comment]
We are following the GNU document https://www.gnu.org/prep/standards/html_node/Errors.html so I'm suprised VSCode doesn't like it

**Comment by Timmmm** [comment]
Ah interesting. Maybe you're the first people to actually use that format! I can't say I've seen it anywhere else.

I'll see how easy it is to add that format to VSCode.

**Comment by Timmmm** [comment]
This is fixed in VSCode now (on `master`), except for the `:startline-endline`, which is difficult to distinguish from `:startline.startcol-endcol` with regex. Not very important though; it will still pick up the start line.
