### ISSUE TITLE
Remove warning about type being already known

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#294]
If you have code like this

    var foo : T = function_that_returns_T();

then Sail will print a warning encouraging you to remove the explicit `: T` annotation

    Redundant type annotation on assignment to foo. Type is already known

However in some cases these explicit type annotations are intentional and desirable even if the type can already be inferred for two reasons:

1. They provide better error checking in case the types change. For example if you update `function_that_returns_T()` to return `S` instead, but `foo` really *must* be a `T` then you will get a sensible and reliable error message with the explicit annotation, but without it the error will move somewhere else - or potentially go unnoticed (e.g. if it is fed into an overloaded function).

2. Sail doesn't have fancy IDE support with type hint inlays yet so it can help with readability.

I think the simplest solution is just to remove the warning. Rust has a similar local type inference system and it does not report a warning in this case.

**Comment by Alasdair** [comment]
Oh, I think the intent was to warn on:
```
var foo : T = something();
foo : T = something_else() // warn here
```
i.e. where the information is being repeated.

I've also seen new users run into issues where they annotate with lots of types that are more general than what we would otherwise infer, and this leads to type errors later when a constraint cannot be proven with the more general annotated types.

**Comment by Timmmm** [comment]
Ah I see, that makes more sense! I totally misread the code that does this and it is actually doing that - in the RISC-V Sail model:

            w_pte : SV48_PTE = update_BITS(pte, pbits.bits());
            w_pte : SV48_PTE = update_Ext(w_pte, ext);

Ignore me. :-)
