### ISSUE TITLE
indexing mistake in is_ones_subrange? shiftl/shiftr in C backend silently drops sign of shift

### ISSUE THREAD

**Issue by cfbolz** [rems-project/sail#300]
I am tracking a problem in the ARM model when booting Linux using Pydrofoil, which triggers an assertion in `shiftl`, that the shift count is negative. This happens when the following [function](https://raw.githubusercontent.com/rems-project/sail-arm/master/arm-v9.3-a/src/v8_base.sail) from the ARM model is run:

```
function AArch64_VAIsOutOfRange (va, acctype, regime, walkparams) = {
    let 'addrtop = AArch64_AddrTop(walkparams.tbid, acctype, walkparams.tbi);
    let 'iasize = AArch64_IASize(walkparams.txsz);
    if HasUnprivileged(regime) then {
        if AArch64_GetVARange(va) == VARange_LOWER then {
            return(not_bool(is_zero_subrange(va, addrtop, iasize)))
        } else {
            return(not_bool(is_ones_subrange(va, addrtop, iasize)))
        }
    } else {
        return(not_bool(is_zero_subrange(va, addrtop, iasize)))
    }
}
```

The assertion comes from the call chain `is_ones_subrange` -> `slice_mask` -> `shiftl`. Looking at [`is_ones_subrange`](https://github.com/rems-project/sail/blob/017de8c90c81b85eb1f37265ddbc38d44b687303/lib/mono_rewrites.sail#L97C1-L118C2) I was confused by the asymmetry between the index manipulation for the arguments to `slice_mask` between `is_ones_subrange` and `is_zero_subrange`:

```
val is_zero_subrange : forall 'n, 'n >= 0.
  (bits('n), int, int) -> bool effect pure

function is_zero_subrange (xs, i, j) = {
  (xs & slice_mask(j, i-j+1)) == extzv([bitzero] : bits(1))
}

...

val is_ones_subrange : forall 'n, 'n >= 0.
  (bits('n), int, int) -> bool effect pure

function is_ones_subrange (xs, i, j) = {
  let m : bits('n) = slice_mask(j,j-i+1) in
  (xs & m) == m
}
```

I think that the `slice_mask` call in `is_ones_subrange` should also look like this: `slice_mask(j, i-j+1)`.

Indeed, the following sail program crashes on the Ocaml backend with an assert, and "works" on the C backend:

```
default Order dec

$include <prelude.sail>
$include <mono_rewrites.sail>

val main : unit -> unit

function main() = {
    let a = 0xffff;
    if is_zero_subrange(a, 3, 1) then print_endline("abc") else print_endline("def");
    if is_ones_subrange(a, 3, 1) then print_endline("abc") else print_endline("def");
}
```

So why does it work on the C backend? Looking at the implementation of [`shiftl`](https://github.com/rems-project/sail/blob/017de8c90c81b85eb1f37265ddbc38d44b687303/lib/sail.c#L1171):

```c
void shiftl(lbits *rop, const lbits op1, const sail_int op2)
{
  rop->len = op1.len;
  mpz_mul_2exp(*rop->bits, *op1.bits, mpz_get_ui(op2));
  normalize_lbits(rop);
}
```

The second argument is converted to an `unsigned long` using `mpz_get_ui`. The [docs](https://gmplib.org/manual/Converting-Integers) of that gmp function say: "The sign of op is ignored, only the absolute value is used." Therefore this hides the bug in `is_ones_subrange`, which simply produces a wrong result.

Possible fixes:

- add an assert to `shiftl` and `shiftr` in the C code to check that the shift amount is non-negative.
- fix `is_ones_subrange`

Does that make sense?

**Comment by bacam** [comment]
Thanks, I've fixed that (modulo the test suite completing successfully), although I've leave whether to add asserts to shifts to @Alasdair.

**Comment by martinberger** [comment]
> _Thanks, I've fixed that (modulo the test suite completing successfully)_

Are we sure there are no more similar mistakes? Maybe fuzzing such support code could be an interesting student project?
