### ISSUE TITLE
SMT solver returned unexpected status 1

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#307]
I am using Sail from commit 27a183e033f858d957758fef8ce34f71319d79c6.

This `test.sail`

```
default Order dec

$include <vector_dec.sail>

function foo() -> bits(definitelydoesntexist) = {
  0b0
}
```

gives this error

```
❯ sail -c test.sail
Error:
SMT solver returned unexpected status 1
```

This was quite tricky to track down. It gives no clue to the location and my actual error was a typo of `bits(r)` instead of `bits(4)` - not obvious!

**Comment by bacam** [comment]
Thanks, I've added the missing check.  Now, just waiting on the CI before merging.
