### ISSUE TITLE
No error on nonexistant overload

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#315]
This compiles without error:

```
$include <prelude.sail>
$include <string.sail>

overload operator ^ = {sdfsdfsdf}
```

I would have expected it to complain about `sdfsdfsdf` not existing.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/316, but we will probably need a PR to sail-riscv first as it has an example of this.
