### ISSUE TITLE
How to avoid bigints in type parameterised struct?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#319]
The `sail-riscv` code has this struct:

```
struct TLB_Entry('asidlen: Int, 'valen: Int, 'palen: Int, 'ptelen: Int) = {
  asid : bits('asidlen),
  global : bool,
  vAddr : bits('valen),      /* VPN */
  pAddr : bits('palen),      /* PPN */
  vMatchMask : bits('valen), /* matching mask for superpages */
  vAddrMask  : bits('valen), /* selection mask for superpages */
  pte : bits('ptelen),       /* PTE */
  pteAddr : bits('palen),    /* for dirty writeback */
  age : bits(64)
}
```

Which is instantiated a few times, e.g.

```
type TLB39_Entry = TLB_Entry(16, 39, 56, 64)
```

The generated C code uses `lbits` for all the `bits('...)` fields *even though we know they will never be more than 64 bits.

```
struct zTLB_Entry {
  uint64_t zage;
  lbits zasid;
  bool zglobal;
  lbits zpAddr;
  lbits zpte;
  lbits zpteAddr;
  lbits zvAddr;
  lbits zvAddrMask;
  lbits zvMatchMask;
};
```

To improve performance, is there a way to avoid this? I can think of a few options:

1. Use `bits(64)` for all the fields, and just extract the relevant bit slices everywhere. This will make the code quite horrible but it will work now.
2. `TLB_Entry`, and all the functions that use it (e.g. `match_TLB_Entry()`) could be monomorphised. Then it would be easy to see where the bitvectors are less than 64 bits.
3. Some kind of type constraint like

```
struct TLB_Entry('asidlen: {Int < 64}, 'valen: {Int < 64}, 'palen: {Int < 64}, 'ptelen: {Int < 64}) = {
```

as far as I can tell from the grammar that isn't currently possible.

4. You can find all the places where TLB_Entry is instantiated and check the maximum values of the type parameters, then it's clear that they're all less than 64. This could lead to slightly odd performance characteristics though - adding `TLB_Entry(65...` somewhere would slow the rest of the program down.

What do you think?

**Comment by Timmmm** [comment]
Btw I tried manually monomorphising `TLB39_Entry` and it increased performance from ~260 kIPS to ~450 kIPS while booting Linux. Pretty significant!

**Comment by Alasdair** [comment]
You can do 
```
struct TLB_Entry('asidlen: Int, 'valen: Int, 'palen: Int, 'ptelen: Int), 'asidlen <= 64 & 'valen <= 64 & 'palen <= 64 & 'ptelen <= 64 = {
    ...
}
```
and it should use a faster representation.

I think we would get quite big gains by using a unknown-length bitvector type with a 'small bitvector' optimization, as is often done for strings.

**Comment by Timmmm** [comment]
Ah amazing, thanks! That did work - it uses `sbits` which I guess makes sense. Unfortunately it didn't lead to the same dramatic speed improvement for some reason. Slightly surprising, but I haven't looked into the generated C.

I'll have to do some systematic benchmarking.

**Comment by Timmmm** [comment]
Actually scratch that - I think I was benchmarking on the wrong branch :-S

It does actually drastically improve performance - not quite to the level of full monomorphising, presumably because of the overhead of the `uint64 len` field and the extra checking, but it gets pretty close:

* Original: ~260 kIPS
* With `'valen <= 64` etc.: ~410 kIPS
* Full manual monomorphising: ~450 kIPS

Small String Optimisation makes lots of sense. `sbits` could already do it really - plenty of space in `len` field for "actually this is a GMP pointer".

**Comment by cfbolz** [comment]
> I think we would get quite big gains by using a unknown-length bitvector type with a 'small bitvector' optimization, as is often done for strings.

Yes, that's one of the big contributing factors to why Pydrofoil is faster. We switch between two different runtime representations of bitvector dynamically. Our bitvector is basically a tagged union (using the width as the tag) between `sbits` and the general gmp implementation. We actually do the same for integers too by having a tagged union between a machine int and gmp. Then we check at runtime whether eg the addition of two ints fits into a machine int and we can switch to the gmp representation if not.

The dynamic checks that are needed for every operation aren't free of course, so having better static analysis to find out the involved bit widths in the Sail compiler is clearly preferable. But the dynamic checks are still cheap compared to calling malloc and free literally all the time.

Doing the same thing in the Sail C backend should not be super hard. I'm happy to help out (but can't really drive the work myself).

**Comment by cfbolz** [comment]
> `sbits` could already do it really - plenty of space in `len` field for "actually this is a GMP pointer".

you don't even need to do anything clever and steal bits from `len`, I think. you can just use the magnitude of `len` itself (if its `<= 64` you use the small representation, otherwise the GMP one).

(unless you want to go for also supporting some kind of sparse bitvector which is larger than 64 bits but only the lowest 64 bits have any `1`s set. We're currently experimenting with that, but I'm not 100% convinced it's super useful).

**Comment by Timmmm** [comment]
Another optimisation opportunity I noticed - as soon as Sail sees that the type might be more than 64 bits, it immediately gives up and uses GMP. For example if you have `bits(128)`, Sail knows it is always 128 bits, so it should theoretically use

```
struct {
   uint64_t x0;
   uint64_t x1;
};
```

which would be much faster than GMP. A ton of work though. Feels like the right thing to do is to abstract out an arbitrary precision integer library that wraps GMP and also supports specifying compile time constraints on types. C is such a pain to work with though...

**Comment by Timmmm** [comment]
Closing this since the question was answered. Created #335 and #336 to track the small int/bitvector stuff.
