### ISSUE TITLE
Merge `var` and `register`?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#320]
It occurred to me that `var` and `register` do the same thing in different contexts. Might it make sense to merge them into one keyword, so that this is more consistent:

| | Immutable | Mutable |
|-|-|-|
| Global |`let`|`register`|
| Local |`let`|`var`|

Unless there's some other difference that I've missed?

**Comment by Alasdair** [comment]
Right now there isn't a big difference, but I think in the future we will want to restrict register types to those that can be sensibly represented in SMT and SystemVerilog, i.e. containing no unbounded types. You can also take references to registers, and not local variables.

In our concurrency tooling, registers can optionally also have more relaxed semantics where writes aren't guaranteed to take place before some kind of barrier.

**Comment by Timmmm** [comment]
Ah ok, thanks for the explanation!
