### ISSUE TITLE
Coverage improvements

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#337]
I've been looking into the Sail branch coverage and would like to send you a PR with a few improvements. It will be a breaking change to the callback API and static branch info file format though so I wanted to get your feedback first. The changes are:

1. Some branches are not recorded because their source code location is not fully tracked. This is the case for `scattered` definitions. I think their location *could* be tracked, but regardless I think we still want to log them so instead I will just return their source location as `"", 0, 0, 0, 0`.
2. There's some confusing name around "branch" because it currently refers to the whole conditional structure (e.g. the `match`) *and* each "arm" of the match. I couldn't find an official name for the "arm"; the closest seems to be "branch target" and that seems reasonable so I propose renaming `coverage_branch_taken` to `coverage_branch_target_taken`.
3. Branches (not branch targets) are not recorded in the static branch info, so add them there. Since it's a breaking anyway change I was thinking of using `B` for the branch and `T` for the branch targets.
4. Add unique IDs for functions and branch targets (i.e. as well as `coverage_branch_count` add `coverage_branch_target_count` and `coverage_function_count`.
5. Add those IDs to the callback arguments.

Adding the IDs allows you to have much faster coverage collection because you don't have to look filenames up in hash tables etc.

Also I was thinking if you just log all the IDs that are taken then you can record the control flow which might be neat for debugging in combination with a "fake" debugger (something like [Retread](https://github.com/pileghoff/retread/tree/main)). Ideally there would be a function exit callback too so you can make a stack trace, but that's not essential.

What do you think? Would a breaking PR like this be acceptable?

**Comment by Alasdair** [comment]
Yes, that all sounds good to me! If you find places without location info we can probably add it.
