### ISSUE TITLE
[ERROR] No package named sail-riscv found.

### ISSUE THREAD

**Issue by quswarabid** [rems-project/sail#357]
I have tried to run this command` opam update && opam install sail-riscv `as mentioned in following.

>               I've released a new sail-riscv package that will hopefully fix the issues you were having. Maybe you could try `opam update && opam install sail-riscv` again?
> 
> _Originally posted by @rmn30 in https://github.com/rems-project/sail/issues/50#issuecomment-495596588_

But I am getting this that there is no package named sail-riscv.

```
quswarabid@quswarabid:~/RISCV/sail-riscv(master)$ opam update && opam install sail-riscv

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[default] no changes from https://opam.ocaml.org
[ERROR] No package named sail-riscv found.
quswarabid@quswarabid:~/RISCV/sail-riscv(master)$
```

**Comment by Alasdair** [comment]
I don't think we release sail-riscv as an opam package anymore. The comment you are referring to is about four years old at this point.

**Comment by quswarabid** [comment]
Very well then, I will close this issue.
