### ISSUE TITLE
Problems with vector update builtin

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#37]
The attached [test.txt](https://github.com/rems-project/sail/files/2961532/test.txt) demonstrates problems with the `vector_update` builtin. Oddly the code type checks OK without a backend but when building c or ocaml I get an error:
```
./sail -ocaml test.txt
Type error:
No val spec found for vector_update
```
Also, the C backend appears to be missing an implementation of vector_update_lbits.

**Comment by Alasdair** [comment]
Should be fixed now
