### ISSUE TITLE
Compilation of type-erasure for unions with type parameters

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#401]
The following program compiles to C with `Sail 0.17.1 (sail @ opam-v2.1.5)` but `clang version 15.0.0 (clang-1500.0.40.1)` rejects it

      union U('t :  Type) = {
        A : ('t, bits(1))
      }
      
      val f : U(unit) -> bits(1)
      function f(u) = {
        match u {
           A(_, bs) => bs
        }
      }
      
      val main : unit -> unit
      function main () = {
        let u : U(unit) = A((), 0b1) in
        let res = f(u) in
        ()
      }

This is a problem of the conversion between `uint64_t` ⁠ and ⁠` lbits `. I can provide details of compilation environment, error messages etc if you need them.  But I think you'll get the same problem locally. cc @Timmmm

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/403 hopefully
