### ISSUE TITLE
Overzealous pattern incompleteness warning for ranges

### ISSUE THREAD

**Issue by nwf-msr** [rems-project/sail#409]
This
```
default Order dec
$include <prelude.sail>
$include <mapping.sail>

val bitvector_popcount : forall ('n : Int), 'n >= 0 . bits('n) -> range(0, 'n)
function bitvector_popcount(v) =
  if 'n == 0 then 0
   else let r = bitvector_popcount(truncateLSB(v, sizeof('n) - 1)) in
        match v[0] { bitzero => r, bitone => r + 1 }

function main() : unit -> unit =
  match bitvector_popcount(0xF00F)
  { 16 => print_endline("All ones")
  , n if n < 16 => print_int("Not all ones:", n)
  }
```
elicits, from 557282b910eb2df1c8c398463870892a45367650,
```
Warning: Incomplete pattern match statement at tmp/test.sail:12.2-7:
20 |  match bitvector_popcount(0xF00F)
   |  ^---^
   |
The following expression is unmatched by unguarded patterns: 17
```
even though `17` is not in the possible range of `bitvector_popcount` with `'n = 16`.

Replacing the existential type with `{'m, 0 <= 'm <= 'n . atom('m)}`, which I suspect is completely equivalent, unsurprisingly triggers the same admonition.

This might be related to #134?

**Comment by Alasdair** [comment]
Do you have this commit? https://github.com/rems-project/sail/commit/ad0c27458fcb2f48ec1996d08f67649877d9e3e7

Prior to that commit I get your output, but after that commit I get:
```
Warning: Incomplete pattern match statement at test.sail:12.2-7:
12 |  match bitvector_popcount(0xF00F)
   |  ^---^
   | 
The following expression is unmatched by unguarded patterns: 0
```
which is within the 0-15 range that is not matched by any clauses without guards

**Comment by nwf-msr** [comment]
Argh, sorry.  I had built from `opam` when I'd meant to build from source.  Apologies for the noise.
