### ISSUE TITLE
Support clog2 type function?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#422]
You can do `2 ^ 'n` in types but as far as I know you can't do the opposite (well, the most useful approximation to opposite): `clog2('n)`. Would it be possible to support that?

This would be useful when you have an integer type that needs to be stored in bits, and you want to work out how many bits to use. E.g.

```
type cap_max_E  = cap_addr_width - cap_mantissa_width + 2
type cap_E_width = clog2(cap_max_E)
```

It's only a mild nice to have thing though so dw if it's really complicated.

**Comment by Alasdair** [comment]
We could definitely add such a function. It might take a bit of extra work if we want the constraint solver to have a good idea of how it works - it doesn't really like exponentials, so we have a bunch of tricks for treating `2 ^` as an uninterpreted function with extra axioms and we might have to do something similar for clog2.

**Comment by Timmmm** [comment]
Ah ok maybe it's not worth the effort then. Feel free to close this!

**Comment by Alasdair** [comment]
It just depends on what type we want, if having `clog2 : int -> int` (or with nat) is ok then it's very straightforward.

We could do something like
```
clog2 : forall 'n, 'n >= 0. int('n) -> {'m, 'n >= 2^'m. int('m)}
```
which would also be very easy, but only captures part of the constraint. If we want to know it returns the smallest such integer at the type level we'd need something like:
```
clog2 : forall 'n, 'n >= 0. int('n) -> int(clog2('n))
```
where `clog2` is also a built-in function at the type-level. However it might lead to additional quantifiers in the generated SMT (to encode the 'smallest number such that...' bit), which would move us away from the nicely-behaved fragment we mostly stick to. It's not obvious that this would be a big problem in practice however.

**Comment by Timmmm** [comment]
My use case is for the latter, so I can do:

```
type cap_max_E : Int = cap_addr_width - cap_mantissa_width + 2 // Evaluates to 24 or 52.
type cap_E_width : Int  = clog2(cap_max_E) // Evaluates to 5 or 6
```

Another example also from CHERI:

```
type cap_size : Int = xlen_bytes * 2
type log2_cap_size : Int = clog2(cap_size)
```

But it only makes the code very slightly worse to not have (currently they're just in two different files that are conditionally selected) that so it's low priority. I think if your `abstract_types` branch is ever done this would be much more useful & critical.

**Comment by Timmmm** [comment]
I think I'll just close this. Now that #431 is fixed I can do it as shown in that issue so this is unnecessary.
