### ISSUE TITLE
SMT solver returned unexpected status 1 with division in integer types

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#426]
```
default Order dec

$include <prelude.sail>

type x : Int = 8

register r : bits(x/2) = 0x0
```

gives

```
Error:
SMT solver returned unexpected status 1
```

(Sorry for the barrage of bugs! I just started writing a large amount of new Sail code for the first time.)

**Comment by Alasdair** [comment]
The error is now more descriptive, whether or not it should be an error is probably better covered by https://github.com/rems-project/sail/issues/427 so I'll close this one as resolved
