### ISSUE TITLE
C: match compilation failure

### ISSUE THREAD

**Issue by Alasdair** [rems-project/sail#429]
```
default Order dec

$include <prelude.sail>

union two_bitvectors('n : Int) = {
    BV1 : bits('n),
    BV2 : bits('n),
}

val get_value32 : two_bitvectors(32) -> bits(32)

function get_value32(tbv) = {
    match tbv {
        BV1(bs) => bs,
        BV2(bs) => bs,
    }
}

register R : bits(32)

val test : forall 'n. bits('n) -> unit

function test(bv) = {
    let x : two_bitvectors('n) = BV2(bv);
    if length(bv) == 32 then {
        R = get_value32(x);
    }
}

val main : unit -> unit

function main() = {
    test(0xABCD_0000);
    print_endline("ok")
}
```
The above program fails when compiling the C with:
```
t.c:149:9: error: assigning to 'uint64_t' (aka 'unsigned long long') from incompatible type 'lbits'
    zbs = ztbv.zBV1;
        ^ ~~~~~~~~~
t.c:157:11: error: assigning to 'uint64_t' (aka 'unsigned long long') from incompatible type 'lbits'
    zuz30 = ztbv.zBV2;
          ^ ~~~~~~~~~
2 errors generated.
```

**Comment by martinberger** [comment]
What was the cause of the problem?

**Comment by Alasdair** [comment]
The code was using the type of the pattern where it should have used the type of the value within the constructor. Normally they are the same, but in this case one is a bitvector of an unknown width, and in the pattern where it is used we know a more precise type so a conversion needs to be added. Because the wrong type was used, the conversion wasn't generated.

**Comment by martinberger** [comment]
But why did it need assignment to a register for this problem to show up?

**Comment by Alasdair** [comment]
oh the register isn't important I think. I could probably minimize the example further to remove it. The problem is the value is created before the `if length(bv) == 32`, so that if statement refines what we know about the type within the constructor after it's created.

**Comment by martinberger** [comment]
BTW, when will the fix go into the Sail compiler distributed with Opam? (Alternatively, what's the commit hash?) I would like to remove the hack I had to make to get around this problem.

**Comment by Alasdair** [comment]
It's this commit
https://github.com/rems-project/sail/commit/ef60a9e2e7500374a5da42eb631f5fa314512615

I'd need to make a new release before it gets in opam. I could do that but
I have a few things that are somewhat in progress right now.
