### ISSUE TITLE
Support _ wildcard in mapping?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#433]
If you try this:

```
mapping Foo : bits(2) <-> int = {
  0b00 <-> 10,
  0b01 <-> 1,
  forwards _ => 5,
  backwards _ => 0b11
}
```

you get a syntax error:

```
Syntax error:
test.sail:9.11-11:
9 |  forwards _ => 5,
  |           ^
  | current token: _
```

I can work around it:

```
mapping Foo : bits(2) <-> int = {
  0b00 <-> 10,
  0b01 <-> 1,
  forwards other => 5,
  backwards other => 0b11
}
```

But it would be nice if `_` worked. Very minor!

**Comment by Alasdair** [comment]
I've added this now, but it's worth mentioning that I can only make it work when the forwards and backwards keywords are present otherwise there's an ambiguity in the grammar. I've added a deprecation warning when the keywords are omitted, which I probably should have already added a while ago.

**Comment by Timmmm** [comment]
Thanks!
