### ISSUE TITLE
Latex output broken?

### ISSUE THREAD

**Issue by rmn30** [rems-project/sail#441]
Sail 17.1 no longer seems to output scattered function clause documentation in `commands.tex`. I haven't tracked down exactly when it stopped working.

**Comment by rmn30** [comment]
FWIW git bisect points the finger at 6ff751c22c9fa17e12e4841c09524f5c89d8c7ec

**Comment by Alasdair** [comment]
Might be fixed by https://github.com/rems-project/sail/commit/0f29616714f99cc2086d40252deac3862fb030ee if I understand the problem correctly

**Comment by rmn30** [comment]
Thanks, this is a big improvement. Unfortunately there is now a new problem with latex output being a bit mangled / invalid. Specifically, if there are comments of the from
```
/*!
 * Paragraph 1
 * 
 * Paragraph 2
 */
```
sail erroneously translates the blank line preceded with `*` to `\emph{` which results in latex errors.  This style is used in the sail-cheri-riscv repo so I assume it used to work.

**Comment by rmn30** [comment]
On further investigation I think the problem only happens if there is not a space after the star. So a blank line with `<space><star><space><newline>`  is fine, but just `<space><star><newline>` emits a stray `\emph{`.

**Comment by Alasdair** [comment]
`*` is markdown for emphasis, so it's not too surprising that happens.

Was the previous behaviour that it stripped those extra `*`s? If that's the case I must have added special support for this style of comments with the special aligned `*` prefixes before I refactored the doc comment handling. If I add that behaviour back I might put it behind a flag, because I'd rather just preserve the contents exactly between the comment start and end (by default at least) going forwards.

**Comment by rmn30** [comment]
Yes, it strips the extra stars. It still works but only for `<space><star><space>...` not `<space><star><newline>`. Not sure whether this is a regression or the trailing spaces got stripped somehow in our Sail source. I can work around now I understand it.

**Comment by rmn30** [comment]
Looks like it's handled in the lexer.

**Comment by Alasdair** [comment]
Oh, I see the code is still there. Not sure why it's broken then.

Doing that in the Lexer will cause issues for the automatic formatting, so we probably should avoid that.

**Comment by rmn30** [comment]
I think it might always have behaved like that it's just our source code had the trailing white space stripped at some point and we didn't notice because it wasn't generating latex.

**Comment by Alasdair** [comment]
Requiring trailing spaces before newlines seems unintentional, I think we can add an extra lexing rule for `wsc+ "*\n"` to handle that case.

**Comment by rmn30** [comment]
Thanks for the recent fixes, unfortunately it is still not quite right. Using the test in this repo:

```
cd test/latex
../../sail -latex candperm.sail
```

The contents of `sail_latex/fclCAndPermMarkdownWithExceptionszexecute33a689e3a631b9b905b85461d3814943.tex` is:

```
 */
function clause #\hyperref[sailzexecute]{execute}#(#\hyperref[sailzCAndPermMarkdownWithExceptions]{CAndPermMarkdownWithExceptions}#(cd, cs1, rs2)) = {
    /* Implementation */
    return ()
```

It looks like the line numbers have become slightly out of whack...

**Comment by rmn30** [comment]
This appears to be related to the fix for the lexing bug: that example contains a line with `<space><star><newline>` and adding a space fixes the output.

**Comment by rmn30** [comment]
Looks like you are missing `Lexing.new_line lexbuf` in that case.
