### ISSUE TITLE
f7087d2 breaks sailcov

### ISSUE THREAD

**Issue by defermelowie** [rems-project/sail#442]
Commit f7087d217cc4ced67cb062038fa91e51c11743ee improves branch coverage output but simultaneously introduces changes to the branch info format that break sailcov. The patch below should adapt sailcov in order to accommodate for these changes but causes the following asserts to fail:
- [`assert (!current_badness == 0);`](https://github.com/rems-project/sail/blob/sail2/sailcov/main.ml#L519)
- [`assert (!current_goodness >= 0);`](https://github.com/rems-project/sail/blob/sail2/sailcov/main.ml#L534)

```diff
diff --git a/sailcov/main.ml b/sailcov/main.ml
index 5f5cff95..3b384f67 100644
--- a/sailcov/main.ml
+++ b/sailcov/main.ml
@@ -120,7 +120,7 @@ module SpanMap = Map.Make (Span)
 module StringMap = Map.Make (String)
 module IntMap = Map.Make (Int)
 
-let add_span spans _ file l1 c1 l2 c2 =
+let add_span spans file l1 c1 l2 c2 =
   StringMap.update (Filename.basename file)
     (fun x ->
       let file_spans = Option.value x ~default:SpanMap.empty in
@@ -134,7 +134,17 @@ let read_more_coverage filename spans =
   try
     let rec loop () =
       let line = input_line chan in
-      spans := Scanf.sscanf line "%c %S, %d, %d, %d, %d" (add_span !spans);
+      spans := begin
+        try
+          match Scanf.sscanf line "%c" (fun n -> n) with
+            | 'T' -> Scanf.sscanf line "%c %d, %d, %S, %d, %d, %d, %d" (fun _type _bid _tid file l1 c1 l2 c2 -> add_span !spans file l1 c1 l2 c2)
+            | 'B' -> Scanf.sscanf line "%c %d, %S, %d, %d, %d, %d" (fun _type _bid file l1 c1 l2 c2 -> add_span !spans file l1 c1 l2 c2)
+            | 'F' -> Scanf.sscanf line "%c %d, %S, %S, %d, %d, %d, %d" (fun _type _fid _id file l1 c1 l2 c2 -> add_span !spans file l1 c1 l2 c2)
+            (* Fall back to old format for unknown types *)
+            |  _  -> Scanf.sscanf line "%c %S, %d, %d, %d, %d" (fun _type file l1 c1 l2 c2 -> add_span !spans file l1 c1 l2 c2)
+            (* Fall back to old format in case of failure *)
+        with Scanf.Scan_failure _ -> Scanf.sscanf line "%c %S, %d, %d, %d, %d" (fun _type file l1 c1 l2 c2 -> add_span !spans file l1 c1 l2 c2)
+      end;
       loop ()
     in
     loop ()
```

**Comment by Alasdair** [comment]
I think those asserts failing means that it considers the code both covered and uncovered simultaneously, which seems like a bug. That might be related to the two different types of coverage points introduced by that patch. I'll have to investigate a bit.

**Comment by Alasdair** [comment]
I figured out what was going on with the asserts. The commit you linked added extra coverage points, but the runtime portion wasn't outputting anything for them which led to covered parts of code contained within uncovered parts (which is what the asserts were guarding against). After I fixed that your patch works:

https://github.com/rems-project/sail/pull/445

**Comment by Alasdair** [comment]
Seems like GitHub doesn't like the Co-authored-by attribution for some reason. I could change it to Reported-by if that's ok with you?

**Comment by defermelowie** [comment]
That's fine for me

**Comment by Alasdair** [comment]
Ok, should be fixed now then!
