### ISSUE TITLE
generation of incorrect lem

### ISSUE THREAD

**Issue by Smattr** [rems-project/sail#47]
Sorry, another one from me... I reduced a problem I'm having to this:

```sh
$ cat test.sail
default Order dec
$include <prelude.sail>

let THIRTY_TWO : atom(32) = 32

val f : bits(32) -> bits(THIRTY_TWO)
$ sail -o test -lem -lem_mwords test.sail
$ lem -isa -outdir . -lib Sail=.../share/src/lem_interp -lib Sail=.../share/src/gen_lib test.lem test_types.lem
File "test.lem", line 55, character 25:
  Syntax error
```

The area of the file Lem is complaining about looks like this:

```lem
 53 | let (THIRTY_TWO : integer) = (32:ii)
 54 |
 55 | val f : Size 'THIRTY_TWO => mword ty32 -> mword 'THIRTY_TWO
 56 |
```

To give some context for my nonsense, what I was originally attempting was to define a `bitfield`, one field of which is a slice whose range is dependent on a constant defined elsewhere. I want to be able to edit one place (the constant) to then affect several parameterised data structures. I figured out that my constant had to be an `atom` which means I awkwardly need to give the value of it twice, but it still isn't usable as the bound of a bit slice. Using it in other places like the above makes me think I'm doing something wrong.

**Comment by bacam** [comment]
Thanks for the report.  This ought to generate a type error because the `let` doesn't introduce a new type variable, but we appear to be missing a well-formed type check on function signatures.

If you add a leading `'` to the names then it should work as you expected:
```
default Order dec
$include <prelude.sail>

let 'THIRTY_TWO : atom(32) = 32

val f : bits(32) -> bits('THIRTY_TWO)
```

Also, you might find using a type constant easier:
```
default Order dec
$include <prelude.sail>

type THIRTY_TWO : Int = 32

val f : bits(32) -> bits(THIRTY_TWO)
```
where you can still get the value back using `sizeof(THIRTY_TWO)`.

**Comment by Smattr** [comment]
Ah, works perfectly! I thought I had tried that but I was using `int` not realising title cased `Int` was different. Thanks!
