### ISSUE TITLE
Potential translation error: No Overloading for vector_subrange in Sail to SystemVerilog Conversion

### ISSUE THREAD

**Issue by yutakang** [rems-project/sail#470]
Hi @Alasdair ,

I've been working on converting a segment of Sail code, based on the Arm-v9.4 specification written in Sail, into SystemVerilog code. However, I've encountered a translation issue that I'm hoping you can help with.

The code segment in question is as follows:

```
default Order dec
$include <prelude.sail>
val UInt0 = pure {
  ocaml: "uint",
  lem: "uint",
  interpreter: "uint",
  c: "sail_unsigned",
  coq: "uint"
} : forall 'n. bits('n) -> {'m, 0 <= 'm < 2 ^ 'n. int('m)}

val UInt1 = pure { coq: "uint" } : forall 'n. (int('n), bits('n)) -> {'m, 0 <= 'm < 2 ^ 'n. int('m)}

function UInt1(n, x) = unsigned(x)

overload UInt = {UInt0, UInt1}

val SInt0 = pure {
  c: "sail_signed",
  _: "sint"
} : forall 'n, 'n > 0. bits('n) -> {'m, - (2 ^ ('n - 1)) <= 'm < 2 ^ ('n - 1). int('m)}

val SInt1 : forall 'n, 'n > 0. (int('n), bits('n)) -> {'m, - (2 ^ ('n - 1)) <= 'm < 2 ^ ('n - 1). int('m)}

function SInt1(n, x) = signed(x)

overload SInt = {SInt0, SInt1}

val IsZero : forall 'n, 'n >= 0. bits('n) -> bool

function IsZero(x) = (x == sail_zeros('n))

val AddWithCarry : forall 'N, 'N > 0. (bits('N), bits('N), bits(1)) -> (bits('N), bits(4))

function AddWithCarry (x, y, carry_in) = {
    let 'unsigned_sum = UInt(x) + UInt(y) + UInt(carry_in);
    let 'signed_sum = SInt(x) + SInt(y) + UInt(carry_in);
    let result : bits('N) = unsigned_sum['N - 1 .. 0];
    let n : bits(1) = [result['N - 1]];
    let z : bits(1) = if IsZero(result) then 0b1 else 0b0;
    let c : bits(1) = if UInt(result) == unsigned_sum then 0b0 else 0b1;
    let v : bits(1) = if SInt(result) == signed_sum then 0b0 else 0b1;
    return((result, ((n @ z) @ c) @ v))
}

val execute: forall 'N, 'N > 0. (bits('N), bits('N), bits(1)) -> (bits('N), bits(4))
function clause execute (a, b, c) = AddWithCarry(a, b, c)
```

Upon attempting the translation from Sail to SystemVerilog, I received the following error for `let result : bits('N) = unsigned_sum['N - 1 .. 0];` in `AddWithCarry`:

```
No overloading for vector_subrange, tried:
 * subrange_bits
   Could not unify bitvector('n) and int('unsigned_sum)
```

To work around this error, I tried substituting `unsigned_sum['N - 1 .. 0]` with `get_slice_int('N, unsigned_sum, 0)`. 
However, I'm concerned that this may not be a suitable alternative.

Could you provide guidance on how to properly address this error? 
Your expertise would be greatly appreciated.

Regards,
Yutaka

**Comment by bauereiss** [comment]
ASL supports this slicing syntax on integers, while Sail doesn't by default, but we have a bit of a hack to add support in the local `prelude.sail` file in the Armv9.4 source tree:

```
val integer_subrange : forall 'hi 'lo, 'lo <= 'hi. (int, int('hi), int('lo)) -> bits('hi - 'lo + 1)
function integer_subrange(i, hi, lo) = get_slice_int(hi - lo + 1, i, lo)

overload vector_subrange = {integer_subrange}
```

It might make sense to include the Arm-specific `prelude.sail` file as a whole rather than the generic `prelude.sail` file from the library?

**Comment by yutakang** [comment]
Hi @bauereiss ,

The Arm-specific `prelude.sail` solved the problem. Thanks!
