### ISSUE TITLE
Source location missing for `Type error` from clashing enum constructors

### ISSUE THREAD

**Issue by martinberger** [rems-project/sail#480]
The compiler does not report source locations for error messages `Type error: E1 is not a subtype of E2` that can arise from name clashes in enums, e.g.
```
enum E1 = { c }
enum E2 = { c }
```
If I use, *mutatis mutandis*,  `union` instead of `enum` then line numbers are reported. This problem is not fixed by https://github.com/rems-project/sail/pull/468 since I'm using the compiler from commit `75fa2459c6b2bf315936f361f1d9bad8ad4199a8` (which fixes https://github.com/rems-project/sail/issues/467).

**Comment by bacam** [comment]
It looks like we don't currently have any collision checking for enum constructors.  Instead, this error comes from checking the generated `undefined_E2` function.  Worse yet, if you don't generate those functions, e.g., due to a scattered definition, then you don't get an error at all.

**Comment by Alasdair** [comment]
I think that's probably just an oversight, shouldn't be too hard to fix.

**Comment by Alasdair** [comment]
Should be fixed now, I also added separate errors for shadowing a register and a global let binding
```
Type error:
test.sail:3.5-6:
3 |enum X = {A, B, C}
  |     ^ Previously defined as part of enum X here
test.sail:5.10-11:
5 |enum Y = {A, D}
  |          ^
  | Enum member A is already part of another enum
```
