### ISSUE TITLE
riscv_duopod.sail does not compile for C

### ISSUE THREAD

**Issue by ctchou** [rems-project/sail#53]
The following code fragment:
```
function rX 0 = EXTZ(0x0)
and rX (r if r > 0) = Xs[r]
```
in sail-riscv/model/riscv_duopod.sail triggers the following error:
```
Internal error: Unreachable code (at "jib/anf.ml" line 516):
[riscv_duopod.sail]:22:12-13
22 |function rX 0 = EXTZ(0x0)
   |            ^
   | Could not convert pattern to ANF: 0
   | 
   | Please report this as an issue on GitHub at https://github.com/rems-project/sail/issues
```
when compiled with the following command line:
```
sail -c prelude.sail riscv_xlen64.sail riscv_duopod.sail
```
The version of Sail I'm using is:
```
Sail 0.9 (sail2 @ opam)
```
On the other hand, neither "sail" without option nor "sail -ocaml" fails on the above code fragment.

Also, the following code fragment:
```
function rX r =
if r == 0 then EXTZ(0x0) else Xs[r]
```
compiles for all three options.

**Comment by Alasdair** [comment]
Thanks for spotting this.

I pushed a fix to the following branch: https://github.com/rems-project/sail/tree/rv_duopod_fix - I'd like to test it a bit more before pushing onto our main branch as the pattern rewriting code interacts with all the various back-ends in sometimes subtle ways.
