### ISSUE TITLE
Semicolon allowed on last expression in block?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#545]
I was a bit surprised that this compiles and works fine:

```
function test() -> bool = {
    true;
}
```

I would have thought it would complain about the semicolon and require

```
function test() -> bool = {
    true
}
```

Just checking if that is intentional?

**Comment by Alasdair** [comment]
Yes, this is intentional. I think the Rust-style trailing semicolon changing the meaning of a block to return unit is not a good fit for Sail, as we want to optimise a little bit more for readability.
