### ISSUE TITLE
`dune build` doesn't work due to warnings

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#555]
`dune build --release` works, but `dune build` generates some warnings-as-errors:

```
File "src/lib/type_error.ml", line 258, characters 8-36:
258 | let rec innermost_function_arg_error l typ err =
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value innermost_function_arg_error.
File "src/lib/pretty_print_sail.ml", line 275, characters 6-21:
275 |   let doc_typschm_typ (TypSchm_aux (TypSchm_ts (_, typ), _)) = doc_typ typ
            ^^^^^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value doc_typschm_typ.
File "src/lib/type_check.ml", line 1890, characters 8-31:
1890 | let rec string_of_overload_tree depth =
               ^^^^^^^^^^^^^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value string_of_overload_tree.
File "src/sail_doc_backend/wavedrom.ml", line 118, characters 11-13:
118 |   | P_app (id, [P_aux (P_id arg, _)]) ->
                 ^^
Error (warning 27 [unused-var-strict]): unused variable id.
File "src/lib/rewrites.ml", line 107, characters 4-18:
107 | let effectful_pexp pexp =
          ^^^^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value effectful_pexp.
File "src/sail_c_backend/c_backend.ml", line 119, characters 4-17:
119 | let ctor_bindings = List.fold_left (fun map (id, ctyp) -> Bindings.add id ctyp map) Bindings.empty
          ^^^^^^^^^^^^^
Error (warning 32 [unused-value-declaration]): unused value ctor_bindings.
File "src/sail_c_backend/c_backend.ml", line 431, characters 63-64:
431 |   let rec analyze_functions ctx f (AE_aux (aexp, ({ env; loc = l; _ } as annot))) =
                                                                     ^
Error (warning 27 [unused-var-strict]): unused variable l.
File "src/sail_c_backend/c_backend.ml", line 1486, characters 23-28:
1486 |         let ctor_args, tuple, tuple_cleanup = (Printf.sprintf "%s op" (sgen_const_ctyp ctyp), empty, empty) in
                              ^^^^^
Error (warning 27 [unused-var-strict]): unused variable tuple.
File "src/sail_c_backend/c_backend.ml", line 1688, characters 10-21:
1688 |       let open Printf in
                 ^^^^^^^^^^^
Error (warning 33 [unused-open]): unused open Stdlib.Printf.
                                                   

```

It would be nice to fix these so that we can promote `ast.ml` to the source directory (which makes ocaml-lsp work with it). Apparently promotion doesn't happen with `--release`. See https://github.com/ocaml/merlin/issues/1761

Since these are all unused warnings can we just delete them? Alternatively disable the 27 and 32 warnings?

**Comment by Alasdair** [comment]
I'm not sure why `dune build --release` doesn't show some warnings - we have the same set enabled for both dev and release.

I basically don't use `dune build` due to the warnings as error thing it does. Last time I looked it seemed the advice was "just use `--release`". Occasionally I run dune build and manually fix any errors that weren't shown with `--release`.

**Comment by Timmmm** [comment]
Ah so I found a way you can disable warnings-as-errors: https://github.com/rems-project/sail/commit/b4e54f40060a5f82374ba0b1c47ba65752c75df4

You can apparently add it globally to a `dune-workspace` file too but I didn't try that.

[Here's a commit](https://github.com/rems-project/sail/compare/sail2...Timmmm:sail:fix_warnings) to just remove the code, but some of it looks like it might be intended to be used? I'm generally a fan of unused variable/function warnings - it catches quite a few mistakes in my experience. It seems like OCaml supports the underscore convention to suppress the warning, so maybe that's a better solution?

**Comment by Alasdair** [comment]
I kept the `string_of` function by using an underscore, but the other ones I removed here: https://github.com/rems-project/sail/pull/560
