### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#569]
Might be nice to do a new release now there are version checking flags and we can do a binary tarball.

**Comment by bacam** [comment]
We should check that the main models come out well on most back-ends first - I'm just fixing an issue that's affecting Coq output for RISC-V that might affect other back-ends too, for example.

**Comment by Alasdair** [comment]
Yes, I think we should do a new release soon. I have some improvements to the documentation generation that I'd like to get out.
