### ISSUE TITLE
Simple REPL question.

### ISSUE THREAD

**Issue by kodyvajjha** [rems-project/sail#588]
A noob question about the REPL: is there a way in the REPL to set and propagate global state of the registers that I define? I see that there is a `:fix_registers` option but that doesn't seem to do what I want. In particular, I want to initialize the registers to a particular value and observe how the instructions change them within a REPL session. It seems like the evaluation scope of an instruction is delimited to its definition.

**Comment by Alasdair** [comment]
Yes, each time we evaluate something the REPL resets the state.

You are right that it would be more useful if it didn't do this, I'll change the behaviour.

**Comment by kodyvajjha** [comment]
Thank you, I tested out the latest commits and it looks very good!
