### ISSUE TITLE
Enum_function's syntax

### ISSUE THREAD

**Issue by trdthg** [rems-project/sail#629]
I'm doing some test on enum

I've checked the manual

![image](https://github.com/rems-project/sail/assets/69898423/493c1290-a6c3-4950-9fff-9e060de8c0c8)

I think the following sail code should be ok:

```
enum func_two_id with fti -> int,
                      fti2 -> int, = {
    fti => {
        1
    },
    fti2 => {
        1
    },
}
```

But there is the error msg:

```
$ ./sail ./test/format/bitfield.sail  // please ignore the filename, just a demo
Error:
./test/format/bitfield.sail:46.11-48.5:
46 |    fti => {
   |           ^
48 |    },
   |----^
   | Each enumeration clause for func_two_id must define exactly 2 expressions for the functions fti, fti2
   | Too few expressions have been given here
```

I checked the related source code(please ignore the changes here):

![image](https://github.com/rems-project/sail/assets/69898423/060d4559-0e98-49f7-a330-66f1d0b3ca2e)

And the following code is ok:

```
fti2 -> int, = {
    fti => (
        {
            1
        },
        {
            1
        },
    ),
    fti2 => (
        {
            1
        },
        {
            1
        },
    ),
}
```

So, is this the correct syntax? Or is there something wrong with initial_check?

If this is a bug, I can help to fix

**Comment by Alasdair** [comment]
```
enum func_two_id with f -> int, g -> int, = {
    fti => (1, 2),
    fti2 => (3, 4),
}
```
The way it's intended to work is that this will generate two functions `f` and `g` that convert the enumeration members into integers, so for the above you would have:
```
f(fti) == 1
f(fti2) == 3
g(fti) == 2
g(fti2) == 4
```
Hopefully that makes sense?

**Comment by trdthg** [comment]
Thanks, then there's no problem :D. (Looking forward to adding it to the docs in the future)
