### ISSUE TITLE
Build fails on Ubuntu 18.04.4 LTS (x86_64)

### ISSUE THREAD

**Issue by ShvadronUzi** [rems-project/sail#65]
I am building Sail on a new Ubuntu 18.04.4 LTS (x86_64) system and I am getting the following error:
I have used opam 1.2 and had similar error then I moved to opam 2.0 (this).
Similar build error with ocaml 4.06.1...
(I tried quite a few configurations....)

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocaml failed at "/gpfs/haifa-h6/00/shvadron/.opam/opam-init/hooks/sandbox.sh build ocaml
        /gpfs/haifa-h6/00/shvadron/.opam/4.07.0/share/ocaml-config/gen_ocaml_config.ml 4.07.0 ocaml".

ERROR while compiling ocaml.4.07.0  
 context     2.0.4 | linux/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.07.0 | https://opam.ocaml.org/#23c4663f
path        /gpfs/haifa-h6/00/shvadron/.opam/4.07.0/.opam-switch/build/ocaml.4.07.0
command     /gpfs/haifa-h6/00/shvadron/.opam/opam-init/hooks/sandbox.sh build ocaml /gpfs/haifa-h6/00/shvadron/.opam/4.07.0/share/ocaml-config/gen_ocaml_config.ml 4.07.0 ocaml
exit-code   1
env-file    /gpfs/haifa-h6/00/shvadron/.opam/log/ocaml-28951-ad8886.env
output-file /gpfs/haifa-h6/00/shvadron/.opam/log/ocaml-28951-ad8886.out
output
OCaml version mismatch: 4.05.0, expected 4.07.0

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
\u250c\u2500 The following actions failed
\u2502 \u03bb build ocaml 4.07.0
\u2514\u2500 
\u2576\u2500 No changes have been performed

---
May be I should start from scratch? How?

**Comment by Alasdair** [comment]
Did you run the `eval $(opam config env)` command?

OCaml 4.05 is the version of ocaml that comes in the ubuntu repositories, so I wonder if the shell hasn't been set up to see the ocaml toolchain installed by opam in ~/.opam

**Comment by ShvadronUzi** [comment]
I removed switch 4.0.6.1 and reinstalled. During the installation one is instructed to use 'opam env' (opam 2.0) and not 'eval $(opam config env)' which return 'Illegal variable'.
Anyway, Sail is cleanly installed now. Case closed.
