### ISSUE TITLE
Sail binary release download location

### ISSUE THREAD

**Issue by jordancarlin** [rems-project/sail#653]
Looking forward to using the new binary release of Sail now that version 0.18 has been released. Unfortunately, it looks like the tarball is currently only available as an artifact within the GitHub action run. 

In addition to GitHub actions artifacts only persisting for 90 days by default, there is no way to easily download them from the command line (they don't have a static download link). Having to download it from within the GitHub actions page is also probably not very discoverable to users.

It would be great if the tarball could be added as one of the assets attached to the release itself. This would make it easily downloadable and visible. For future releases we can probably adjust the GitHub actions workflow to do this automatically, but it might be necessary to manually add it to the 0.18 release to avoid having to create a new release.

**Comment by Timmmm** [comment]
Yeah that was what I was thinking. In other projects I've had it automatically attach the artifacts to releases (e.g. [here](https://github.com/Timmmm/autorebase/blob/ea257cae8d61ffcf2a5bb15c61806f4ac08fb5b3/.github/workflows/release.yml#L57)), but you end up with a kind of confusing flow where you have to make a draft release, then trigger CI, then it attaches the artifact, then you publish it. Bit confusing IMO, so I thought we could do it manually initially. (I don't have permission to do it though.)

Also, yeay, new release - thanks!!

**Comment by Timmmm** [comment]
Once it is available as a Github release attachment I'll update the RISC-V model's CI to use that instead of OPAM.

**Comment by jordancarlin** [comment]
@Alasdair any update on when we can expect this to be available? Maybe for this first binary release it can just get attached manually and then we can explore automatically linking it/using GitHub attestation for future releases. Would be good to get this out soon so that people upgrading to Sail 0.18 can do it using the binary release instead of Opam.

**Comment by bacam** [comment]
Alasdair is away this week, so you'll probably get a response next week.

**Comment by Timmmm** [comment]
Here's a copy of the artifact in case it gets deleted before Alasdair gets to this. (And this means I can prototype using it in riscv-sail CI).

[sail.zip](https://github.com/user-attachments/files/16799744/sail.zip)

**Comment by Alasdair** [comment]
I am just looking into Github artifact attestations right now, so I'll give that a try first.

**Comment by Alasdair** [comment]
Tried it on my fork and it seems to work pretty nicely!
```
$ gh attestation verify ~/Downloads/sail.tar.gz --owner Alasdair                                     08/29/24 15:21:40 PM
Loaded digest sha256:0a93d112537a29a91539381973df20de5e26e6c9473ce3364d61c1b1e4d3a033 for file:///Users/alasdair/Downloads/sail.tar.gz
Loaded 1 attestation from GitHub API
✓ Verification succeeded!
```

**Comment by Alasdair** [comment]
Should be available here now https://github.com/rems-project/sail/releases
