### ISSUE TITLE
Built in 2^ operator requires spaces

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#657]
It's slightly odd that the built-in `2 ^` support requires spaces around `^`, but if you define a custom `operator ^` it doesn't. The RISC-V sail model defines `operator ^ = {int_power}` which means it will actually give different type checking results if you use spaces or not (because `2 ^` is understood at the type level, but `int_power` is just `int ^ int -> int`).

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/660
