### ISSUE TITLE
SMT backend: struct bitvector length problems

### ISSUE THREAD

**Issue by PRugg-Cap** [rems-project/sail#679]
There seems to be a difference between conservative bitvector widths generated in datatype definitions, and the width of constants generated, which are more precise. This causes z3 to generate an error.

```
$include <generic_equality.sail>

struct MyStruct = { f : range(0,1) }

let my_struct : MyStruct = struct { f = 0 }

$property
function prop() -> bool = my_struct.f == 0
```

`sail -smt test.sail` with the latest sail2 generates the following SMT2:

```
...
(declare-datatypes ((ZMyStruct 0)) (((ZMyStruct (ZMyStruct_zf (_ BitVec 64))))))
(assert (not (= (ZMyStruct_zf (ZMyStruct #b0)) #x0000000000000000)))
(check-sat)
```

z3 throws:
```
(error "line 5 column 44: unknown constant ZMyStruct ((_ BitVec 1)) 
declared: (declare-fun ZMyStruct ((_ BitVec 64)) ZMyStruct) ")
```

Thanks so much for the quick fixes to my previous issues. I held off on this one because it seemed like it might be related to them or one of my workarounds.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/680
