### ISSUE TITLE
SMT backend: generated SMT files have very long lines

### ISSUE THREAD

**Issue by PRugg-Cap** [rems-project/sail#682]
Thanks to all your help with fixes, and a few of my own I'll hopefully be able to PR in soon, I'm able to run some real properties again. Unfortunately, on some of the trickier properties, Sail is hanging and burning through lots of RAM when trying to generate the SMT2 files (i.e. not the SMT checking itself, but generating the problems). Trying to reduce down the problem, it seems there are cases where Sail will generate some *very* long lines (hundreds of thousands of characters in the biggest examples I get that still finish). I've tried to reproduce it more artificially. Here's a fairly pathological example that I think shows what happens:
```
default Order dec

$include <vector_dec.sail>
$include <arith.sail>
$include <generic_equality.sail>

// Some arbitrary non-trivial function
$property
function check(v : bits(64)) -> bool = {
  assert ((v[0] == bitzero & v[63..32] == v[31..0]) | (v[1] == bitzero & v[63..32] == v[31..0]));
  true
}

$property
function prop2(v : bits(64), a : bool) -> bool = {
  if a then check(v)
       else check(v)
}

$property
function prop4(v : bits(64), a : bool) -> bool = {
  if a then prop2(v, a)
       else prop2(v, a)
}

$property
function prop8(v : bits(64), a : bool) -> bool = {
  if a then prop4(v, a)
       else prop4(v, a)
}

$property
function prop16(v : bits(64), a : bool) -> bool = {
  if a then prop8(v, a)
       else prop8(v, a)
}

$property
function prop32(v : bits(64), a : bool) -> bool = {
  if a then prop16(v, a)
       else prop16(v, a)
}
```

Here, prop32.smt2 has a 52,000 character line corresponding to working out whether any of the asserts get hit. Amusingly, it starts out with anding together the variable corresponding to `a` 254 times, so seems there's some room for optimisation. Presumably the path conditions get anded even when they're already a subset of one another... Beyond that, I'd have hoped that defining some intermediates could help, but possible that's naive of me.

Note:
- While this example has the same condition at each level and all the checks are the same, it's not true of the example I'm interested in, i.e. while noticing both branches are the same would help in some cases, it probably won't get to the bottom of the issue.
- It may well be fundamental that this can't work well with SMT. The case I started from used to work before the refactor, but then I guess the point was the path condition tracking wasn't sound!

**Comment by PRugg-Cap** [comment]
Ah, perhaps more relevant, `check.smt2` is sat but `prop2` and onwards are unsat. Presumably it's supposed to come up as sat if an assert can fail, which is clearly the case here (change the assert to `assert(false)` to make that clearer)?

**Comment by Alasdair** [comment]
I merged a new SMT simplifier a few days ago: If you try with https://github.com/rems-project/sail/commit/05113ceb08733a61dd3e55c485033e4d24de41d0 you might see significantly smaller files. I get a prop32.smt2 that is only 6510 characters.

I think the other issue is to do with functions marked as either `$property` or `$counterexample` calling other functions marked as such. If you remove the directives from everything example prop32 it seems to work. For each function we insert a preamble that encodes the function type constraints into the generated SMT and I think this is interacting with the inlining in a weird way.

**Comment by PRugg-Cap** [comment]
Thanks! It seems to help a lot. One of my properties is still causing the compiler to get stuck, but I'll have to look at it in more detail to see if there's any obvious potential for improvement.

Reassuring about the spurious unsats. Agreed that's a weird thing to do: I only added that in towards the end so I could see the sizes of all the files that get generated without having to edit the example file.

I'll close this for now, and possibly reopen it if I get to the bottom of my remaining issue. Thanks for your help!
