### ISSUE TITLE
c2: -O produces incorrect C code (in particular with slice function)

### ISSUE THREAD

**Issue by julienfreche** [rems-project/sail#72]
I created a small example that is problematic:

```
$include "prelude.sail"

type xlen : Int = 64
type xlen_bytes : Int = 8
type xlenbits = bits(xlen)
type regbits = bits(5)

val zeros : forall 'n, 'n >= 0. atom('n) -> bits('n)
function zeros n = replicate_bits(0b0, n)

/* Architectural state */

register PC : xlenbits
register nextPC : xlenbits

register Xs : vector(32, dec, xlenbits)
/* Getters and setters for X registers (special case for zeros register, x0) */
val rX : regbits -> xlenbits effect {rreg}

function rX(r) =
  match r {
    0b00000 => EXTZ(0x0),
    0b11111 => EXTZ(slice(PC, 0, 32)),
    _ => Xs[unsigned(r)]
  }

val wX : (regbits, xlenbits) -> unit effect {wreg}

function wX(r, v) =
  if r != 0b00000 then {
    match r {
      _ => Xs[unsigned(r)] = v
    }
  }

overload X = {rX, wX}

/* Instruction decode and execute */
enum iop = {RISCV_ADDI}
scattered union ast

val decode : bits(32) -> option(ast) effect pure

val execute : ast -> unit effect {rmem, rreg, wreg}

/* ****************************************************************** */

/* ADDI */

union clause ast = ITYPE : (bits(12), regbits, regbits, iop)

function clause decode imm : bits(12) @ rs1 : regbits @ 0b000 @ rd : regbits @ 0b0010011
  = Some(ITYPE(imm, rs1, rd, RISCV_ADDI))

function clause execute (ITYPE (imm, rs1, rd, RISCV_ADDI)) =
  let rs1_val = X(rs1) in
  let imm_ext : xlenbits = EXTS(imm) in
  let result = rs1_val + imm_ext in
  X(rd) = EXTS(slice(result, 0 , 32))

function clause decode _ = None()
```

When compiled with:
`sail -c2 -O simple.sail`

It produces C code that is not correct:

```
cc -g -I lib_sail/ -I generated_lib/  -c -o generated_lib/out.o generated_lib/out.c
generated_lib/out.c:2127:51: error: use of undeclared identifier 'PC'
    zgaz34 = (safe_rshift(UINT64_MAX, 64 - 32) & (PC >> INT64_C(0)));
```

This should say: `state->PC`

It seems like this issue only occurs when optimizations are turned on. This can also be reproduced by trying 'c2' on the ARM model

I did a bit of debugging (but didn't complete it due to lack of time/unfamiliarity with the code base). My guess is that one node in the AST should say 'Global' rather than 'Name'.

**Comment by Alasdair** [comment]
Yes it is very likely that the global/local name distinction I introduced for the updated -c2 backend has some weird corner cases. I'll look into this.

With PLDI keeping me busy this week I haven't been able to test it as much as I'd like, it's still very experimental and I haven't had the time to update and test riscv and ARM yet.

**Comment by julienfreche** [comment]
I appreciate the quick reply. Of course, I understand this is experimental and wasn't expecting this to work out of the box :) But, I am still able to experiment quite a bit with it so that's a promising start for me. It's likely that I will give more feedback as I progress.
