### ISSUE TITLE
hex_str doesn't convert negative numbers correctly

### ISSUE THREAD

**Issue by Timmmm** [rems-project/sail#725]
Slightly funny one but

```
print_endline(hex_str(-10));
```

prints

```
0x-a
```

**Comment by Timmmm** [comment]
Using this in `sail.c` works for the lowercase version:

```
void hex_str(sail_string *str, const mpz_t n)
{
  sail_free(*str);
  gmp_asprintf(str, "%#Zx", n);
}

void hex_str_upper(sail_string *str, const mpz_t n)
{
  sail_free(*str);
  gmp_asprintf(str, "%#ZX", n);
}
```

Unfortunately for the uppercase one it makes the `x` uppercase too.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/726

I didn't look for any better gmp_asprintf options and just check if the argument is negative and print the absolute value with a minus sign if it is is.
