### ISSUE TITLE
c2: ARM model: the generated C code contains duplicated struct members

### ISSUE THREAD

**Issue by julienfreche** [rems-project/sail#73]
I can reproduce the issue by running:

```
sail -c2 -O -non_lexical_flow -no_lexp_bounds_check -memo_z3 -no_warn -dno_cast  model/prelude.sail model/no_devices.sail model/aarch_types.sail model/aarch_mem.sail model/aarch64.sail model/aarch64_float.sail model/aarch64_vector.sail model/aarch32.sail model/aarch_decode.sail model/elfmain.sail
```

And then compiling the C code:
```
gcc -c -O2 out.c -DHAVE_SETCONFIG  -I ../../sail//lib/
In file included from out.c:1:
./out.h:6553:28: error: duplicate member 'CNT_CTL'
    zz5vecz8z6z8z5bv32z9z9 CNT_CTL;
                           ^
./out.h:6552:28: note: previous declaration is here
    zz5vecz8z6z8z5bv32z9z9 CNT_CTL;
```

**Comment by bacam** [comment]
This should be fixed in the git repo (after the recent release).  Could you give that a try?

**Comment by bacam** [comment]
Apologies, wrong issue!

**Comment by julienfreche** [comment]
I cannot reproduce this issue anymore on master with the ARM model. Probably a recent change fixed that? Or maybe a side-effect from the fix for https://github.com/rems-project/sail/issues/72

I will let the maintainers decide what to do with the issue, on my side, it's ok to close.

**Comment by julienfreche** [comment]
I may have spoken too fast. It sounds like the issue only appears when including elfmain.sail, I had removed that file from my testing code but adding it back reproduces this issue.

**Comment by julienfreche** [comment]
The model shows:

```
val read_register = "reg_deref" : forall ('a : Type). register('a) -> 'a effect {rreg}

//             EL1 physical        EL2 physical        EL3 physical        EL1 virtual,       EL2 virtual
let CNT_CVAL = [ref CNTP_CVAL_EL0, ref CNTHP_CVAL_EL2, ref CNTPS_CVAL_EL1, ref CNTV_CVAL_EL0, ref CNTHV_CVAL_EL2]
let CNT_TVAL = [ref CNTP_TVAL_EL0, ref CNTHP_TVAL_EL2, ref CNTPS_TVAL_EL1, ref CNTV_TVAL_EL0, ref CNTHV_TVAL_EL2]
let CNT_CTL  = [ref CNTP_CTL_EL0,  ref CNTHP_CTL_EL2,  ref CNTPS_CTL_EL1,  ref CNTV_CTL_EL0,  ref CNTHV_CTL_EL2 ]
let CNT_CTL  = [ref CNTP_CTL_EL0,  ref CNTHP_CTL_EL2,  ref CNTPS_CTL_EL1,  ref CNTV_CTL_EL0,  ref CNTHV_CTL_EL2 ]
let CNT_IRQ  = [0x0000_000d,       0x0000_000a,        0x0000_03ff,        0x0000_000b,       0x0000_03ff       ]
//                                                     No IRQ                                 No IRQ?
```

So, the model itself contains a duplicate. Is that expected?

**Comment by julienfreche** [comment]
@Alasdair isn't this a bug in the model? Why is CNT_CTL defined twice?

**Comment by Alasdair** [comment]
Yes it's a bug in the model, the second one can be removed

I guess it's because it treats top-level letbindings like those in functions and assumes they can shadow each other, but we should probably have a check that forbids this.

**Comment by Alasdair** [comment]
Duplicate top-level let bindings will now trigger a type error

**Comment by julienfreche** [comment]
perfect! thanks
