### ISSUE TITLE
"Accidentally quadratic" behavior in typechecker?

### ISSUE THREAD

**Issue by nwf** [rems-project/sail#771]
This function from the CHERIoT model,
```
val capToString : (Capability) -> string
function capToString (cap) = {
  let len = getCapLength(cap);
  let len_str = BitStr(to_bits(cap_len_width + 3, len));
  let (base, top) = getCapBoundsBits(cap);
  let top_str = BitStr(0b000 @ top);
  BitStr(cap.address)
    ^ " (v:" ^ (if cap.tag then "1 " else "0 ")
    ^ BitStr(base) ^ "-" ^ top_str
    ^ " l:" ^ len_str
    ^ " o:" ^ BitStr(cap.otype)
    ^ " p:"
    ^ (if cap.global then "G " else "- ")
    ^ (if cap.permit_load then "R" else "-")
    ^ (if cap.permit_store then "W" else "-")
    ^ (if cap.permit_load_store_cap then "c" else "-")
    ^ (if cap.permit_load_mutable then "m" else "-")
    ^ (if cap.permit_load_global then "g" else "-")
    ^ (if cap.permit_store_local_cap then "l " else "- ")
    ^ (if cap.permit_execute then "X" else "-")
    ^ (if cap.access_system_regs then "a " else "- ")
    ^ (if cap.permit_seal then "S" else "-")
    ^ (if cap.permit_unseal then "U" else "-")
    ^ (if cap.perm_user0 then "0)" else "-)")
}
```
really sends the typechecker for a spin (I have never let it run long enough to terminate, but see below).  Replacing the last line with
```
   ^ (if cap.perm_user0 then "0" else "-")
   ^ ")"
```
makes it almost instantaneous.

Looking at some growth curves just for fun... replacing the last expression above with
```
  BitStr(cap.address)
    ^ (if cap.perm_user0 then "0)" else "-)")
```
generates 116 lines of output from `dtc-verbose 1` (which might be a surrogate statistic for steps of the checking algorithm).  Adding the `permit_unseal` line above that makes it 324.  Further adding `permit_seal`, 1750.  Then 11732, 81606, ....  By contrast, the workaround above (`^ ")"`) completes in a mere 489 steps.

**Comment by Alasdair** [comment]
I think it's because the `")"` literal immediately resolves the operating overloading of `^` to be string only. Because `^` is right-associative, it will look at
```
    (if cap.global then "G " else "- ")
    ^ (if cap.permit_load then "R" else "-")
    ^ (if cap.permit_store then "W" else "-")
    ^ (if cap.permit_load_store_cap then "c" else "-")
    ^ (if cap.permit_load_mutable then "m" else "-")
    ^ (if cap.permit_load_global then "g" else "-")
    ^ (if cap.permit_store_local_cap then "l " else "- ")
    ^ (if cap.permit_execute then "X" else "-")
    ^ (if cap.access_system_regs then "a " else "- ")
    ^ (if cap.permit_seal then "S" else "-")
    ^ (if cap.permit_unseal then "U" else "-")
    ^ (if cap.perm_user0 then "0)" else "-)")
```
before it sees the first `" p:"` literal.

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/773

The approach we have is to filter the space of possible operator overloadings using some heuristics. There are certainly other cases where those heuristics won't work and we'll fall back to checking all possible operator combinations. I think those cases should be less likely in practice though.

**Comment by nwf** [comment]
Thank you!
