### ISSUE TITLE
TC: overly terse type checking failure message with bitvector mappings

### ISSUE THREAD

**Issue by nwf** [rems-project/sail#775]
Using c706e190, this incorrect program, minimized from the RISC-V model as I'm making my way through the chore of `struct`-uralizing register selectors for https://github.com/riscv/sail-riscv/issues/523,
```
default Order dec
$include <prelude.sail>

struct regidx = { regidx : bits(5) }

scattered union ast

val encdec : ast <-> bits(32)
scattered mapping encdec

union clause ast = UTYPE : (bits(20), regidx)
mapping clause encdec = UTYPE(imm, rd) <-> imm @ rd @ 0b0010111
```
indeed fails to typecheck.  However, the entirety of the error message is
```
Type error:
Expected bitvector type, got regidx
```
which is a little... austere.  Adding `-dtc_verbose 1` at least gives some hint of where the error is, so it's not catastrophic, but still.

(The corrected version, with `mapping clause encdec = UTYPE(imm, struct { regidx = rd }) <-> imm @ rd @ 0b0010111`, compiles just fine.)

**Comment by Alasdair** [comment]
Should be fixed by https://github.com/rems-project/sail/pull/776

**Comment by nwf** [comment]
Thank you! :heart:
