### ISSUE TITLE
sail from opam can't build c files for arm (syntax error)

### ISSUE THREAD

**Issue by Trolldemorted** [rems-project/sail#80]
How should we invoke sail (the version from opam) to build c files? I ran into #54, but the solution there was to use the Makefile which doesn't work with the installed sail version.

I modified your Dockerfile to include the arm folder, the arm Makefile to use the installed sail and include a `armV8.c` target, and the docker entrypoint to invoke make:
```diff
diff --git a/Dockerfile b/Dockerfile
index 4db0ce5f..c03b1bc9 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -19,4 +19,5 @@ RUN eval `opam env` && \
 COPY --chown=opam docker_entry_point.sh /home/opam/
 RUN chmod +x docker_entry_point.sh
 WORKDIR /data
+COPY arm arm
 ENTRYPOINT ["/home/opam/docker_entry_point.sh"]
diff --git a/arm/Makefile b/arm/Makefile
index c597f714..de7c51d8 100644
--- a/arm/Makefile
+++ b/arm/Makefile
@@ -1,4 +1,4 @@
-SAIL:=../src/sail.native
+SAIL:=sail
 LEM:=../../lem/lem
 
 # the order of the files is important
@@ -14,6 +14,9 @@ SOURCES=armV8.h.sail\
 
 all: armV8.lem armV8.ml armV8_embed.lem
 
+armV8.c: $(SOURCES)
+	$(SAIL) -c $(SOURCES)
+
 armV8.lem: $(SOURCES)
 	$(SAIL) -lem_ast -o armV8 $(SOURCES)
 
diff --git a/docker_entry_point.sh b/docker_entry_point.sh
index d66b202a..cb27955d 100644
--- a/docker_entry_point.sh
+++ b/docker_entry_point.sh
@@ -1,2 +1,2 @@
 #!/bin/sh
-eval `opam env` && sail $*
+eval `opam env` && cd arm && make armV8.c
```

When I run the container, sail prints the same error @jrprice reported:
```
sail_1  | sail -c armV8.h.sail armV8_A64_sys_regs.sail armV8_A64_special_purpose_regs.sail armV8_A32_sys_regs.sail armV8_pstate.sail armV8_lib.h.sail armV8_common_lib.sail armV8_A64_lib.sail armV8.sail
sail_1  | Syntax error:
sail_1  | [armV8.h.sail]:1:0-0
sail_1  | 1 |(*========================================================================*)
sail_1  |   |^
sail_1  |   | current token: (
sail_1  | make: *** [Makefile:18: armV8.c] Error 1
```

**Comment by Alasdair** [comment]
The version in that subdirectory was out of date. There is a more up-to-date version of that model in the aarch64_small, but it's only been used for some small concurrency things. I've just deleted the old folder from the repo now, so other people don't run into the same issue.

We have a translated version of the ARM ASL specification here:

https://github.com/rems-project/sail-arm

**Comment by Trolldemorted** [comment]
Thanks for the quick response!

Is your ASL->SAIL translation tool able to create models for other arm variants, e.g. Armv7-A?

**Comment by Alasdair** [comment]
Currently it's only been used on the v8-A ASL, I don't know if there are any public releases for v7, but there are likely things that are specific to the v8 spec in the translator.

We have been planning on making it public, but I don't think that has happened yet.
