### ISSUE TITLE
Sail coverage: support concurrent sail models

### ISSUE THREAD

**Issue by PeterRugg** [rems-project/sail#86]
Currently, sail-compiled code spits its coverage data out into a "sail_coverage" file. It seems there is no locking, so concurrent sail-compiled programs running from the same directory will concurrently write to "sail_coverage", causing it to be corrupted.

Currently I have hacked around the issue with the following change to lib/coverage/src/lib.rs, ensuring every program produces a fresh sail_coverage file by incrementing a counter on the filename until the file does not exist, but I'm no Rust expert. My change will currently also go wrong if there is an error on opening the file other than that the file already exists.
```
 #[no_mangle]
 pub extern "C" fn sail_coverage_exit() -> c_int {
-    if let Ok(mut file) = OpenOptions::new().create(true).append(true).open("sail_coverage") {
-        if !write_locations(&mut file, 'B', &BRANCHES) {
-            return 1
+    for i in 0.. {
+        if let Ok(mut file) = OpenOptions::new().create_new(true).append(true).open(format!("sail_coverage{}", i)) {
+            if !write_locations(&mut file, 'B', &BRANCHES) {
+                return 1
+            }
+            if !write_locations(&mut file, 'F', &FUNCTIONS) {
+                return 1
+            }
+            break
         }
-        if !write_locations(&mut file, 'F', &FUNCTIONS) {
-            return 1
-        }
-        0
-    } else {
-        1
     }
+    0
 }
```
Would it be possible to have some upstream support for fixing this issue?

**Comment by Alasdair** [comment]
Maybe a better way to do this would be to have an option when you compile with coverage support that sets the file name? Then you would get one coverage file per test, which could be concatenated to give the total coverage?

**Comment by PeterRugg** [comment]
Hmm, I'm actually often running the same sail-compiled binary on different input files, so a runtime option would be preferable if possible?

**Comment by Alasdair** [comment]
Ok, that makes sense. How about exposing a function:
```
void sail_set_coverage_file(const char *output_file);
```
that you could then set via the emulator options?

**Comment by PeterRugg** [comment]
Yep, that sounds like a good solution, thanks.

**Comment by Alasdair** [comment]
Ok I just pushed a commit that adds that, let me know how it goes

**Comment by PeterRugg** [comment]
Sorry for the extreme delay, but this works great - thanks!
